### ISSUE TITLE
'Stepped' charging plan unnecessarily stops charging

### ISSUE THREAD

**Issue by gcoan** [springfall2008/batpred#1484]
**Describe the bug**
Today we had a 2 hour free electricity power up event (on a lowish solar day) so I wanted to take maximum benefit of this.
Prior to the event predbat had done freeze discharges so my 9.5kWh battery was just over half full and the 5.2 was empty - in 2 hours of charging both should therefore be filled.

![image](https://github.com/user-attachments/assets/b4f00949-1d08-4075-9599-652fff228b76)

Predbat's plan was to charge for the two hours, BUT it had steps of 62, 67, 100 and 100% SoC.

Both batteries started charging at 15:00

At 15:20 the 9.5 battery was at 65%, the 5.2 at 17%.  Since the 9.5 was above the 'step target' for that slot, Predbat put the 9.5 inverter into pause charge mode turned off the planned charge:
![image](https://github.com/user-attachments/assets/823388c1-07b0-4d6a-9ab9-85c6f8d468f4)
![image](https://github.com/user-attachments/assets/d1119384-25fe-4897-b887-fe997ca8ec02)
![image](https://github.com/user-attachments/assets/820cd79f-3bbd-4d43-8ea9-33eb78b893b3)

I tried setting the battery to force charge for the 2 hour period but this made no difference, the stepped plan stopped the 9.5 battery from charging when it should have been in the free electricity.  The only way I could get the 2 hour charging to complete was to put predbat into read only mode and manually turn both charge schedules on again.

**Expected behavior**
Preferable solution:

Predbat takes account of battery capacity in setting the SoC target for each slot rather than setting a single SoC target that is just the average of the multiple battery SoC's.  This would give much better control of multi-inverter setups with differing battery capacities, something predbat doesn't handle very well at present (all batteries are assumed to be the same size).

Alternative solution:

When charging for a period of time at the same rate (in this case 2 hours at 100%), simply set the target rate to the end SoC target for the period rather than devising intermediate (and false) targets for the charging period.

**Predbat version**
8.4.9

**Environment details**
2024.9.2
2x GE Hybrid inverters, one with a 9.5, one with a 5.2 battery.

**Log file**
[appdaemon.log.2.log](https://github.com/user-attachments/files/17121445/appdaemon.log.2.log)

**Comment by springfall2008** [comment]
Interesting issue, let me think about how to fix

**Comment by springfall2008** [comment]
Would something like this work, where instead of setting flag SOC% you set the % based on the charge you plan to add for each battery?

The only thing is some might end up full so really you would want to account for that when setting the SOC target on the others....

    def adjust_battery_target_multi(self, inverter, soc, is_charging):
        """
        Adjust target SOC based on the current SOC of all the inverters accounting for their
        charge rates and battery capacities
        """
        required_kwh = self.soc_max * (soc / 100.0)
        add_this = required_kwh * (inverter.battery_rate_max_charge / self.battery_rate_max_charge)
        new_soc_kwh = min(inverter.soc_kwh + add_this, inverter.soc_max)
        new_soc_percent = calc_percent_limit(new_soc_kwh, inverter.soc_max)
        self.log("Inverter {} adjust target soc to {}% based on requested all inverter soc {}%".format(inverter.inverter_id, new_soc_percent, soc))
        inverter.adjust_battery_target(new_soc_percent, is_charging)

**Comment by gcoan** [comment]
yes that sounds like a good approach @springfall2008 

Even as a first step to just add the SoC % increment to the charge-to target would stop the 'stopping prematurely' problem from occurring which is my problem at the moment.

Getting more sophisticated with working out those adjustments based on battery limits would be a nice further enhancement but not as critical to fixing the problem.  And if one battery does get full before the other then the excess will just get exported or (with the fast response gen 1 firmware or gen 2/3 behaviour) the other inverter will soak it up rather than let it get exported.

**Comment by springfall2008** [comment]
A test version is on 'main', can you please check?

**Comment by gcoan** [comment]
> A test version is on 'main', can you please check?

Will do. I'll install it now, the plan has lots of charging tonight

**Comment by gcoan** [comment]
The main version was working fine but ;ooks like it crashes when trying to set the charge up:

```
2024-09-29 22:17:03.473007 INFO pred_bat: Adjust idle time, charge 22:30:00-23:00:00 discharge 00:00:00-00:00:00
2024-09-29 22:17:03.478644 INFO pred_bat: Adjust idle time computed idle is 22:10:00-22:30:00
2024-09-29 22:17:03.480345 INFO pred_bat: Error: Exception raised 'Inverter' object has no attribute 'inverter_id'
2024-09-29 22:17:03.484360 INFO pred_bat: Error: Traceback (most recent call last):
  File "/homeassistant/appdaemon/apps/batpred/predbat.py", line 11119, in update_time_loop
    self.update_pred(scheduled=False)
  File "/homeassistant/appdaemon/apps/batpred/predbat.py", line 9963, in update_pred
    status, status_extra = self.execute_plan()
                           ^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/batpred/predbat.py", line 8754, in execute_plan
    self.adjust_battery_target_multi(inverter, self.charge_limit_percent_best[0], isCharging)
  File "/homeassistant/appdaemon/apps/batpred/predbat.py", line 8346, in adjust_battery_target_multi
    inverter.inverter_id, soc, soc_percent, new_soc_percent, self.dp2(add_kwh), self.dp2(add_this), self.dp2(new_soc_kwh)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Inverter' object has no attribute 'inverter_id'

2024-09-29 22:17:03.535631 INFO pred_bat: Info: record_status Error: Exception raised 'Inverter' object has no attribute 'inverter_id'
```

reverted back to 8.4.9, restarted appdaemon, clean run through, re-installed main, error:

```
2024-09-29 22:39:32.468258 INFO pred_bat: Error: Exception raised 'Inverter' object has no attribute 'inverter_id'
2024-09-29 22:39:32.474312 INFO pred_bat: Error: Traceback (most recent call last):
  File "/homeassistant/appdaemon/apps/batpred/predbat.py", line 11184, in update_time_loop
    self.update_pred(scheduled=False)
  File "/homeassistant/appdaemon/apps/batpred/predbat.py", line 10009, in update_pred
    status, status_extra = self.execute_plan()
                           ^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/batpred/predbat.py", line 8800, in execute_plan
    self.adjust_battery_target_multi(inverter, self.charge_limit_percent_best[0], isCharging)
  File "/homeassistant/appdaemon/apps/batpred/predbat.py", line 8384, in adjust_battery_target_multi
    self.log("Inverter {} adjust target soc for hold to {}% based on requested all inverter soc {}%".format(inverter.inverter_id, new_soc_percent, soc))
                                                                                                            ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Inverter' object has no attribute 'inverter_id'

2024-09-29 22:39:32.517622 INFO pred_bat: Info: record_status Error: Exception raised 'Inverter' object has no attribute 'inverter_id'
2024-09-29 22:39:32.530460 WARNING AppDaemon: Excessive time spent in callback 'update_time_loop() in pred_bat', Thread 'thread.thread-1' - now complete after 184.529682 seconds (limit=120.0)
```

And I noticed that despite the crash, the error attribute in predbat.status is still set to false, it should be set to true...

![image](https://github.com/user-attachments/assets/c4fbbfeb-9761-4c87-ab4c-59f17562b881)

reverted back to 8.4.9, restarted appdaemon, all running OK now

[appdaemon.log](https://github.com/user-attachments/files/17181462/appdaemon.log)

**Comment by springfall2008** [comment]
This crash is now fixed.

I released a beta version 8.4.10 which is the same as 'main' for now.

**Comment by gcoan** [comment]
I did do some screen shots of 8.4.10, and there is a bit of feedback on potentially needing to look at the charge rate (so I'll share those separately), but we're in a power up event right now and I can see the different limits being applied to each inverter:

Plan says to charge to 79% then 85 then 100:
![image](https://github.com/user-attachments/assets/5f733170-b14f-4c2c-93fc-24e3d9aba5da)

But the two inverters are on different SoC's which normally cause a problem with the stepped charge rates, however Predbat is now setting the target SoC for each differently:
![image](https://github.com/user-attachments/assets/16b5aa9c-3d0e-4939-ae4b-22c155ed467e)

**Comment by gcoan** [comment]
Bit later on and I am seeing effects of the stepped charging still not quite being right.

overall target for the half hour slot is 85%

![image](https://github.com/user-attachments/assets/68c58058-85a4-4e8c-b7d9-b7ff84c98b3f)

target for inverter G 87% (SoC 84%), H 81% (SoC 74%)

but as G is quite close to the target SoC the inverter has slowed the charge rate down to 1.2kWh rather than the 2.4kWh it should be going at
![image](https://github.com/user-attachments/assets/16fc96da-c113-4368-b2b3-77bc9a2cc6ea)

the target SoC needs to be set higher to stop this happening

Can see that the target SoC is being progressively refined by Predbat
![image](https://github.com/user-attachments/assets/b467694e-6a87-422f-a27b-182008a8edc1)

**Comment by chalfontchubby** [comment]
@gcoan since you raised this one, wanted to check in - are you happy to close this if it's resolved for you now, or would it be worth raising a fresh issue if there's still something specific to chase? We're trying to focus the backlog on live issues.
