### ISSUE TITLE
Unnecessary charging after 100% SOC

### ISSUE THREAD

**Issue by Yuffi17** [springfall2008/batpred#1873]
**Describe the bug**
I don't know if this is the same issue I had before or if it is a new one. The evening/night plan shows excessive charging. 
By "excessive" I mean predbat plans to charge to 100% and then continue to charge when this is neither necessary to meet load nor economically sensible.

**Expected behaviour**
I have 19kWh available and a daily use of about 14kWh so expect a 2/3 cycle of the batteries. I don't mind charging to 100% to have some spare, but to start charging at10:30pm and continue charging (to 100%) until 11:30am seems crazy. 

I expected predbat to select the cheapest slots to charge my battery, and then stop charging so I can use energy from the battery to meet the house load.

**Predbat version**
8.10.2

**Environment details**
- Inverter and battery setup: GE Hybrid 5kW inverter with 2xGivBatt 9.5kWh batteries

**Screenshots**
![image](https://github.com/user-attachments/assets/790e3d16-cd0a-4a50-b258-43f5a21d03d5)

I know this shows the longer term plan which is subject to change, but predbat sems to be struggling at the moment and I don't understand why.  This particular plan has persisted despite predbat running several times (it's not a one off plan that disappears on the next run).

**Predbat debug yaml file**
[predbat_debug_15_00_00.yaml.txt](https://github.com/user-attachments/files/18412197/predbat_debug_15_00_00.yaml.txt)

**Comment by gcoan** [comment]
Do you have low charge mode turned on?  I have noticed some weird behaviour in #1866 with low power charge mode.

Its not entirely due to low power mode as turning this switch off Predbat still holds the SoC at 100% through the morning peak like you are getting

**Comment by springfall2008** [comment]
Oddly this appears to be caused by 'metric_self_sufficiency' as if you set it to 0 the problem goes away. I'll take a look as to why as it appears to be a bug

**Comment by Yuffi17** [comment]
Today's plan is also a bit dodgy (charging when not needed) so I have just tried setting metric_self_sufficiency to zero 0 to see the difference, but there wasn't any real change. 

I've taken a debug log of this plan so you can see. I only screen-grabbed the start of the plan - there's enough here to see it doesn't need to charge and the debug file has the full story anyway.

![Image](https://github.com/user-attachments/assets/1fcc1341-fc5e-4a63-ada7-beb0945adb31)

[predbat_debug_11_15_00.yaml.txt](https://github.com/user-attachments/files/18464229/predbat_debug_11_15_00.yaml.txt)

**Comment by springfall2008** [comment]
Good spot, I found a potential fix which I have pushed to 'main' for testing.

**Comment by Yuffi17** [comment]
Thanks! 
I've loaded Main (8.11.1) and run it a couple of times to let the plan settle. Unfortunately I'm still seeing charging after 100%. The plan does a really good job of picking the best slots to charge from up to 100%, it's just a bit over enthusiastic once the target is reached.

![Image](https://github.com/user-attachments/assets/e1109626-529b-4a6b-86a7-5b4eafcf806d)

[predbat_debug_16_10_00.yaml.txt](https://github.com/user-attachments/files/18465216/predbat_debug_16_10_00.yaml.txt)

**Comment by springfall2008** [comment]
I find if you set metric_self_sufficiency to 0 and best_soc_keep to 2 then the plan looks reasonable. I'm struggling to figure out why self sufficiency makes things worse.

**Comment by Yuffi17** [comment]
I think it may be some interplay between Predbat and the varying rates of Agile. I know someone who has two AIO and was running Predbat on agile with the same problem - they swapped to cosy and the Predbat plan is now behaving as expected. I'll try to find out more info.

The original introduction of self_sufficiency was to provide a way to bias the plan towards the GE eco mode (meeting house load from battery where possible). I realise this sort of goes against the original "maximise return" aim of Predbat because they try to reduce low gain charge/discharge, and retain some battery capacity rather than making full use of it. 

I don't understand the code well enough to help properly, but I do have some questions: perhaps they might help spark some thoughts?
- Does Predbat assemble the best plan from a set of different models, and is it getting confused at this stage? I have seen the plan change back and forth sometimes as it updates (not got screen shots or debugs because I can't tell when this will happen)
- Is the excessive charging a form of hold charge? Sometimes the plan shows green charge to 100% and sometimes blue hold charge at 100% but both have the same effect. I have also seen plans swap between the two states.
- The issue I am seeing happens after the battery system reaches 100% SOC - I can't recall seeing such behaviour at the end of a charge slot that results in less than 100%. So what triggers the plan to stop charging? Or possibly, what is preventing the plan from recognising the 100% has been reached?
- Why does the plan seem to be stable on a tariff with fixed rates and unstable on Agile? What is it about the varying rates that causes this charging over-run?

Sorry I can only offer questions and not answers. And many thanks for all the time you spend trying to get this working perfectly for those of us who don't understand the code!

**Comment by springfall2008** [comment]
Okay I've spent quite a bit of time looking at this and I can offer an explanation.

You have your losses set as

5% - charge
5% - discharge
6% - inverter

This means to charge the battery from grid and then supply it to your home you have losses of

1.05 x 1.06 x 1.06 x 1.05 = 23.9%

If you sit at 100% battery then none of these losses apply.

That means a 27.12p import slot when at 100% costs about the same as a 21.9p charge slot. 

If for example I change the inverter loss back to 3% then a get more of the plan you might expect.

The default loss values are 3% charge, 3% discharge and 4% inverter loss. How did you pick your figures?


![Image](https://github.com/user-attachments/assets/47d9e441-ade9-4874-9603-90055f02c62c)

**Comment by Yuffi17** [comment]
Ok - that makes sense.

I took my loss figures from easyPV and the GivEnergy data sheets. I can't find the system efficiency data on easyPV anymore to check the values. The GE hybrid inverter sheet says 94% charge/discharge efficiency and 97.5% PV efficiency. 

If this means the inverter loses about 2.5% (dc panels to mains) and the battery side loses 3.5% then in effect I have entered the same figure twice. I'm happy to try the defaults.

Question: Does metric_self_sufficiency affect the comparison of import slot price to charge slot price?

**Comment by gcoan** [comment]
In tests I've seen on the GivEnergy community most people have concluded that total round trip losses are in the range 10-20%.  Some people take 15% as a mid point and others 20% as an easy approximation.

The losses are surprisingly higher than you think they would be, but does look like yours are a bit high.
For comparison mine are 0.055, 0.05 and 0.04 - its your inverter loss that is making the big difference as its applied twice in charging and discharging the battery

**Comment by springfall2008** [comment]
I would not include any PV Losses in this calculation, instead either adjust your Solcast settings or use pv_scaling to account for that.

**Comment by Yuffi17** [comment]
Thanks. I really appreciate the help and advice. I'll adjust the figures and see how things go.

**Comment by dabeeeenster** [comment]
I'm seeing similar behaviour on my new install: 

<img width="945" height="594" alt="Image" src="https://github.com/user-attachments/assets/b0f547d8-9c81-4fc9-a816-7c820df5a600" />

My losses are set as follows:

<img width="875" height="203" alt="Image" src="https://github.com/user-attachments/assets/76df1a29-06db-4693-93cf-a28c46368dce" />

Log: 

[predbat (2).log](https://github.com/user-attachments/files/24414766/predbat.2.log)

Debug:

[predbat_debug (2).yaml](https://github.com/user-attachments/files/24414767/predbat_debug.2.yaml)

app.yaml

```yaml
# Taken from https://github.com/springfall2008/batpred/blob/main/templates/solaredge.yaml

pred_bat:
    module: predbat
    class: PredBat

    # Sets the prefix for all created entities in HA - only change if you want to run more than once instance
    prefix: predbat

    # Timezone to work in
    timezone: Europe/London

    # If you are using Predbat outside of HA then set the HA URL and Key (long lived access token here)
    ha_url: "http://192.168.1.10:8123"
    ha_key: "xxx.eyJpc3MiOiJiMzU2MjhhMzlkNTQ0MzJhODcwYWVhMDQyODQ2ODhjNCIsImlhdCI6MTc2MjIxMjI1NCwiZXhwIjoyMDc3NTcyMjU0fQ.9tI5ozUBKvXWSCdT6osd5Cf6-e062pZiATAgSONqlWE"

    # Currency, symbol for main currency second symbol for 1/100s e.g. $ c or £ p or e c
    currency_symbols:
        - "£"
        - "p"

    # Days previous is the number of days back to find historical load data
    # Recommended is 7 to capture day of the week but 1 can also be used
    # if you have more history you could use 7 and 14 (in a list) but the standard data in HA only lasts 10 days
    days_previous:
        - 1

    # Days previous weight can be used to control the weighting of the previous load points, the values are multiplied by their
    # weights and then divided through by the total weight. E.g. if you used 1 and 0.5 then the first value would have 2/3rd of the weight and the second 1/3rd
    days_previous_weight:
        - 1

    # Number of hours forward to forecast, best left as-is unless you have specific reason
    forecast_hours: 48

    # The number of hours ahead to count in charge planning (for cost estimates)
    # It's best to set this on your charge window repeat cycle (24) but you may want to set it higher for more variable
    # tariffs like Agile
    forecast_plan_hours: 48

    # Set the frequency in minutes that this plugin is run
    # recommend something that divides by 60 (5, 10 or 15) or you won't trigger at the start of energy price slots
    run_every: 5

    # Number of threads to use in plan calculation
    # Can be auto for automatic, 0 for off or values 1-N for a fixed number
    threads: auto

    # Controls/status - must by 1 per inverter
    num_inverters: 1
    inverter_type: "SE"

    # Sensors, currently more than one can be specified and they will be summed up automatically
    # however if you have two inverters only set one of them as they will both read the same.
    #
    # DONE
    load_today:
        - sensor.solar_house_consumption_kwh
        # Think this is wrong - what I had originally before 01/01/2026
        # - sensor.solaredge_i1_ac_energy
        # There is also sensor.solaredge_i1_m1_ac_power which is the net from the grid - not just the battery

    # DONE
    import_today:
        # This doesnt exist for me but shows up here https://github.com/springfall2008/batpred/discussions/2451
        # - sensor.solaredge_m1_imported
        # This might be wrong - what I had originally before 01/01/2026
        - sensor.solaredge_i1_m1_ac_energy_imported
    # DONE
    export_today:
        # This might be wrong - what I had originally before 01/01/2026
        - sensor.solaredge_i1_m1_ac_energy_exported
        # This doesnt exist for me but shows up here https://github.com/springfall2008/batpred/discussions/2451
        # - sensor.solaredge_m1_exported

    # This was missing from the solaredge template
    # DONE
    grid_power:
        - sensor.solaredge_i1_m1_ac_power
    grid_power_invert:
        - False
    # DONE
    battery_power:
        - sensor.solaredge_i1_b1_dc_power
    battery_power_invert:
        - True

    # Not 100% needed as per docs https://springfall2008.github.io/batpred/inverter-setup/#solaredge-inverters
    # DONE
    pv_today:
        - sensor.solar_panel_production_kwh # This is a custom template sensor - see SolarEdge section of 'Inverter Setup' documentation for how to create

    # maximum battery charge rate. If you have a single battery then can use the b1_max_charge_power sensor directly
    # DONE
    battery_rate_max:
        - sensor.solaredge_i1_b1_max_charge_power
    # DONE
    charge_rate:
        - number.solaredge_i1_storage_charge_limit
    # DONE
    discharge_rate:
        - number.solaredge_i1_storage_discharge_limit

    # DONE
    pv_power:
        - sensor.solar_panel_production_w # This is a custom template sensor - see SolarEdge section of 'Inverter Setup' for details
    # DONE
    load_power:
        - sensor.solar_house_consumption_w # This is a custom template sensor - see SolarEdge section of 'Inverter Setup' for details
    # DONE
    soc_percent:
        - sensor.solaredge_i1_b1_state_of_energy
    # DONE
    soc_max:
        - sensor.solaredge_i1_b1_maximum_energy

    #charge_limit:
    #    - number.solaredge_i1_ac_charge_limit

    # removed as per https://github.com/springfall2008/batpred/issues/2670
    #scheduled_charge_enable:
    #  - off
    #scheduled_discharge_enable:
    #  - off

    # Services to control charging/discharging
    charge_start_service:
        service: select.select_option
        entity_id: "select.solaredge_i1_storage_command_mode"
        option: "Charge from Solar Power and Grid"
        repeat: True
    charge_stop_service:
        service: select.select_option
        entity_id: "select.solaredge_i1_storage_command_mode"
        option: "Maximize Self Consumption"
    discharge_start_service:
        service: select.select_option
        entity_id: "select.solaredge_i1_storage_command_mode"
        option: "Discharge to Maximize Export"
        repeat: True

    # Inverter max AC limit (one per inverter)
    inverter_limit_charge:
        - 2200
    inverter_limit_discharge:
        - 2200

    # Some inverters don't turn off when the rate is set to 0, still charge or discharge at around 200w
    # The value can be set here in watts to model this (doesn't change operation)
    #inverter_battery_rate_min:
    #  - 200

    # Some batteries tail off their charge rate at high soc%
    # enter the charging curve here as a % of the max charge rate for each soc percentage.
    # the default is 1.0 (full power)
    #battery_charge_power_curve:
    #  91 : 0.91
    #  92 : 0.81
    #  93 : 0.71
    #  94 : 0.62
    #  95 : 0.52
    #  96 : 0.43
    #  97 : 0.33
    #  98 : 0.24
    #  99 : 0.24
    #  100 : 0.24

    # Inverter clock skew in minutes, e.g. 1 means it's 1 minute fast and -1 is 1 minute slow
    # Separate start and end options are applied to the start and end time windows, mostly as you want to start late (not early) and finish early (not late)
    # Separate discharge skew for discharge windows only
    inverter_clock_skew_start: 0
    inverter_clock_skew_end: 0
    inverter_clock_skew_discharge_start: 0
    inverter_clock_skew_discharge_end: 0

    # Clock skew adjusts the Appdaemon time
    # This is the time that Predbat takes actions like starting discharge/charging
    # Only use this for workarounds if your inverter time is correct but Predbat is somehow wrong (AppDaemon issue)
    # 1 means add 1 minute to AppDaemon time, -1 takes it away
    clock_skew: 0

    # Set these to match solcast sensor names if not using the cloud interface
    # The regular expression (re:) makes the solcast bit optional
    # If these don't match find your own names in Home Assistant
    pv_forecast_today: re:(sensor.(solcast_|)(pv_forecast_|)forecast_today)
    pv_forecast_tomorrow: re:(sensor.(solcast_|)(pv_forecast_|)forecast_tomorrow)
    pv_forecast_d3: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_3|d3))
    pv_forecast_d4: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_4|d4))

    # car_charging_energy defines an incrementing sensor which measures the charge added to your car
    # is used for car_charging_hold feature to filter out car charging from the previous load data
    # Automatically set to detect Wallbox and Zappi, if it doesn't match manually enter your sensor name
    # Also adjust car_charging_energy_scale if it's not in kwH to fix the units
    car_charging_energy: "sensor.myenergi_zappi_charge_added_session"

    num_cars: 1

    # car_charging_planned is set to a sensor which when positive indicates the car will charged in the upcoming low rate slots
    # This should not be needed if you use Octopus Intelligent Slots which will take priority if enabled
    # The list of possible values is in car_charging_planned_response
    # Auto matches Zappi and Wallbox, or change it for your own
    car_charging_planned:
        - "re:(sensor.wallbox_portal_status_description|sensor.myenergi_zappi_plug_status)"

    car_charging_planned_response:
        - "yes"
        - "on"
        - "true"
        - "connected"
        - "ev connected"
        - "charging"
        - "paused"
        - "waiting for car demand"
        - "waiting for ev"
        - "scheduled"
        - "enabled"
        - "latched"
        - "locked"
        - "plugged in"
        - "waiting"

    ## To make planned car charging more accurate, either using car_charging_planned or Octopus Intelligent
    ## specify your battery size in kwh, charge limit % and current car battery soc % sensors/values
    ## If you have intelligent the battery size and limit will be extracted from Intelligent directly
    ## Set the car SOC% if you have it to give an accurate forecast of the cars battery levels
    ## One entry per car if you have multiple cars
    car_charging_battery_size:
        - 70
    car_charging_limit:
        - "input_number.predbat_car_synthetic_charge_limit"
    car_charging_soc:
        - "sensor.xxx"

    octopus_api_account: "A-xxx"
    octopus_api_key: "xxx"

    # Carbon Intensity data from National grid
    # carbon_intensity: "re:(sensor.carbon_intensity_uk)"
    # carbon_postcode: "N22 7XH"
    # carbon_automatic: True

    # Octopus saving session points to the saving session Sensor in the Octopus plugin, when enabled saving sessions will be at the assumed
    # Rate is read automatically from the add-in and converted to pence using the conversion rate below (default is 8)
    # octopus_saving_session: "re:(binary_sensor.octopus_energy([0-9a-z_]+|)_saving_session(s|))"
    # octopus_saving_session_octopoints_per_penny: 8

    # Octopus free session points to the free session Sensor in the Octopus plugin
    # Note: You must enable this event sensor in the Octopus Integration in Home Assistant for it to work
    # octopus_free_session: "re:(event.octopus_energy_([0-9a-z_]+|)_octoplus_free_electricity_session_events)"

    # Energy rates
    # Please set one of these three, if multiple are set then Octopus is used first, second rates_import/rates_export and latest basic metric

    # Set import and export entity to point to the Octopus Energy plugin
    # automatically matches your meter number assuming you have only one
    # Will be ignored if you don't have the sensor
    # Or manually set it to the correct sensor names e.g:
    # sensor.octopus_energy_electricity_xxxxxxxxxx_xxxxxxxxxxxxx_current_rate
    # sensor.octopus_energy_electricity_xxxxxxxxxx_xxxxxxxxxxxxx_export_current_rate
    # metric_octopus_import: "re:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_current_rate)"
    # metric_octopus_export: "re:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_export_current_rate)"

    # Standing charge can be set to a sensor (e.g. Octopus) or manually entered in pounds here (e.g. 0.50 is 50p)
    # metric_standing_charge: "re:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_current_standing_charge)"

    # Or set your actual rates across time for import and export
    # If start/end is missing it's assumed to be a fixed rate
    # # Gaps are filled with 0
    # rates_import:
    #     - start: "23:30:00"
    #       end: "05:30:00"
    #       rate: 7.5
    #     - start: "05:30:00"
    #       end: "23:30:00"
    #       rate: 30.0

    # rates_export:
    #     - rate: 15.0

    # For pv estimate, leave blank for central estimate, or add 10 for 10% curve (worst case) or 90 or 90% curve (best case)
    # If you use 10 then disable pv_metric10_weight below
    # pv_estimate: 10

    # Battery scaling makes the battery smaller (e.g. 0.9) or bigger than its reported
    # If you have an 80% DoD battery that falsely reports it's kwh then set it to 0.8 to report the real figures
    battery_scaling: 1.0

    # Can be used to scale import and export data, used for workarounds
    import_export_scaling: 1.0

    dno_region: "C"
    compare_list:
        - id: "current"
          name: "Current Tariff"
        - id: "eon_next_drive"
          name: "Eon Next Drive import/Fixed export"
          rates_import:
              - rate: 6.7
                start: "00:00:00"
                end: "07:00:00"
              - rate: 24.86
                start: "07:00:00"
                end: "00:00:00"
          rates_export:
              - rate: 16.5
        - id: "igo_fixed"
          name: "Intelligent GO import/Fixed export"
          rates_import_octopus_url: "https://api.octopus.energy/v1/products/INTELLI-VAR-24-10-29/electricity-tariffs/E-1R-INTELLI-VAR-24-10-29-{dno_region}/standard-unit-rates/"
          rates_export_octopus_url: "https://api.octopus.energy/v1/products/OUTGOING-VAR-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-24-10-26-{dno_region}/standard-unit-rates/"
        - id: "igo_agile"
          name: "Intelligent GO import/Agile export"
          rates_import_octopus_url: "https://api.octopus.energy/v1/products/INTELLI-VAR-24-10-29/electricity-tariffs/E-1R-INTELLI-VAR-24-10-29-{dno_region}/standard-unit-rates/"
          rates_export_octopus_url: "https://api.octopus.energy/v1/products/AGILE-OUTGOING-19-05-13/electricity-tariffs/E-1R-AGILE-OUTGOING-19-05-13-{dno_region}/standard-unit-rates/"
        - id: "go_fixed"
          name: "GO import/Fixed export"
          rates_import_octopus_url: "https://api.octopus.energy/v1/products/GO-VAR-22-10-14/electricity-tariffs/E-1R-GO-VAR-22-10-14-{dno_region}/standard-unit-rates/"
          rates_export_octopus_url: "https://api.octopus.energy/v1/products/OUTGOING-VAR-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-24-10-26-{dno_region}/standard-unit-rates/"
        - id: "go_agile"
          name: "GO import/Agile export"
          rates_import_octopus_url: "https://api.octopus.energy/v1/products/GO-VAR-22-10-14/electricity-tariffs/E-1R-GO-VAR-22-10-14-{dno_region}/standard-unit-rates/"
          rates_export_octopus_url: "https://api.octopus.energy/v1/products/AGILE-OUTGOING-19-05-13/electricity-tariffs/E-1R-AGILE-OUTGOING-19-05-13-{dno_region}/standard-unit-rates/"
        - id: "agile_fixed"
          name: "Agile import/Fixed export"
          rates_import_octopus_url: "https://api.octopus.energy/v1/products/AGILE-24-10-01/electricity-tariffs/E-1R-AGILE-24-10-01-{dno_region}/standard-unit-rates/"
          rates_export_octopus_url: "https://api.octopus.energy/v1/products/OUTGOING-VAR-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-24-10-26-{dno_region}/standard-unit-rates/"
        - id: "agile_agile"
          name: "Agile import/Agile export"
          rates_import_octopus_url: "https://api.octopus.energy/v1/products/AGILE-24-10-01/electricity-tariffs/E-1R-AGILE-24-10-01-{dno_region}/standard-unit-rates/"
          rates_export_octopus_url: "https://api.octopus.energy/v1/products/AGILE-OUTGOING-19-05-13/electricity-tariffs/E-1R-AGILE-OUTGOING-19-05-13-{dno_region}/standard-unit-rates/"
        - id: "flux"
          name: "Flux import/Export"
          rates_import_octopus_url: "https://api.octopus.energy/v1/products/FLUX-IMPORT-23-02-14/electricity-tariffs/E-1R-FLUX-IMPORT-23-02-14-{dno_region}/standard-unit-rates"
          rates_export_octopus_url: "https://api.octopus.energy/v1/products/FLUX-EXPORT-23-02-14/electricity-tariffs/E-1R-FLUX-EXPORT-23-02-14-{dno_region}/standard-unit-rates"
        - id: "cosy_fixed"
          name: "Cosy import/Fixed export"
          rates_import_octopus_url: "https://api.octopus.energy/v1/products/COSY-22-12-08/electricity-tariffs/E-1R-COSY-22-12-08-{dno_region}/standard-unit-rates"
          rates_export_octopus_url: "https://api.octopus.energy/v1/products/OUTGOING-VAR-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-24-10-26-{dno_region}/standard-unit-rates/"

    # Export triggers:
    # For each trigger give a name, the minutes of export needed and the energy required in that time
    # Multiple triggers can be set at once so in total you could use too much energy if all run
    # Creates an entity called 'binary_sensor.predbat_export_trigger_<name>' which will be turned On when the condition is valid
    # connect this to your automation to start whatever you want to trigger

```

**Comment by gcoan** [comment]
I don't see anything particularly wrong with that plan.

Predbat is charging your battery on the rates up to 19p and holding the battery full running off grid until the rates increase to 21p when it starts discharging the battery to meet house load. 

You've not included the full plan so can't tell when your battery runs out and predbat next plans charging but this does not look excessive behaviour.

If you turn plan debug on you can see the effective rates including inverter and battery losses

**Comment by dabeeeenster** [comment]
Ah ok my confusion was based on the action of charge for several 30m segments when the battery is already at 100%? Is that expected?

**Comment by gcoan** [comment]
By setting charge to 100% this will hold the battery fully charged for those slots. 

It is quite normal, it's how predbat does it. If the SoC wasn't being released when rates increase then it'd be a problem which is what the original issue was suggesting.

There are losses from charging and discharging the battery and if it's more economical to run direct off grid then predbat will do that.

**Comment by dabeeeenster** [comment]
Thanks for the explanation. How is this different from the original post on this issue? Or is the original post the same use case?

**Comment by gcoan** [comment]
The original post did identify a bug which has been fixed and the OP confirmed it was better, but had some comments about why the battery was being held and not released,  the explanation then for the plan behaviour was down to the losses that had been configured meant it was uneconomical to use the battery.   Your case is not really the same, predbat is just holding the battery full until the rates drop.

I'm going to close as this issue was resolved originally
