### ISSUE TITLE
New Gen3 Single phase high voltage inverter and batteries

### ISSUE THREAD

**Issue by TheSargey** [springfall2008/batpred#2366]
Hi folks, hope you're well.

I mentioned a while back I was upgrading to the latest GE inverter and batteries, it's 10kW inverter (Single phase) paired with 20kW of HV batteries.

Seems like the kit is still in it's infancy, had big issues getting the battery firmware upgraded (ended up having to go via USB direct into the battery stack) but we're up and running today.  Pretty frightening to see it suddenly pulling 10kW from the grid to charge the battery!

Anyway, I digress.  One issue I've got (which I've raised with GE directly) is the local modbus connection seems to vanish after a couple of hours, however the cloud information continues to work.  A quick restart of the inverter allows GivTCP to get it's connection back and things work as expected.

Whilst GE looks into this, I'm just looking at the restart options I have available in apps.yaml - namely:

  # When enabled automatic restart will restart the add-on if communication fails
  # Example below is auto-restart for GivTCP add-on itself
  auto_restart:
    - shell: 'rm -rf /homeassistant/GivTCP/*.pkl'
    - service: hassio/addon_restart
      addon: 533ea71a_givtcp

  #  Example on how to restart the inverter via GivTCP
  #  - service: switch.turn_on
  #    entity_id: switch.givtcp_{geserial}_reboot_invertor

If I simply enable the inverter restart by removing the hashes on the last two lines, does this send a restart via the cloud or locally?  I'm guessing locally, however the problem I have is there is no local control when the inverter "disappears" however I can restart the inverter via the app/cloud.  Just trying to get it so that predbat can restart the inverter when the clock skews and REST becomes unavailable (which is basically the sign that the inverter has for some reason gone to sleep locally).

Just wanted to get your thoughts on this.

Thanks as always for your help.

Sarge

**Comment by gcoan** [comment]
All such commands are made via GivTCP locally through modbus, so wouldn't work for you.

Might be worth looking at the GivEnergy API's to see if there is an API to poke the inverter to restart itself.

Alternatively why not use the GE cloud integration already built into predbat and get the data from the cloud rather than locally via GivTCP.  https://springfall2008.github.io/batpred/inverter-setup/#givenergy-with-ge_cloud

I have used the older method of the ge_cloud integration that Trefor wrote when I had an issue with accidentally zapping all the history of my givtcp import sensor, so predbat broke,  and using that cloud integration worked perfectly.

Also, are you sure it is an inverter issue?  Have you tried the latest beta or dev versions of givtcp in case its fixed there?

**Comment by TheSargey** [comment]
Hi Geoff, thanks as always for your advice.

I was looking at the GE Cloud integration, I can give that a go for sure.

I think it's definitely a GE issue rather than a GivTCP as I lose the local connection for the GE app at the same time as losing GivTCP, which suggests to me it's the inverter "shutting shop" and disallowing local network connection somehow.  What do you think?

Also, I have an issue with PredBat updating the charge/discharge rate for the inverter to 10kW when I'm trying to keep this to around 7kW until I update the breaker I've got in the consumer unit.  I've set in apps.yaml the rate (7000) but for some reason it's forcing GivTCP to reset this to 10000 - I've ascertained it's PredBat as I can set it to read only and the update doesn't happen via GivTCP, but if I let PredBat take control it changes the charge/discharge rate that I've set directly in the inverter... Here's the line in GivTCP
Setting battery charge rate 8240 was a success
2025-05-14 22:53:36,394 - GivTCPHV - write       -  [INFO    ] - Setting battery charge rate 8240 was a success
2025-05-14 22:53
It says 8240 but when I look at the inverter it's set it to 10000.  I'm not sure what setting in PredBat would be forcing this to max, would you know off the top of your head?

Many thanks as always,

Sarge

**Comment by TheSargey** [comment]
I think I found it - inverter_limit_charge and discharge - just testing this now

**Comment by TheSargey** [comment]
> I think I found it - inverter_limit_charge and discharge - just testing this now

This worked, had to set it to 5000 in yaml and it worked out to 7170 in the inverter.

**Comment by gcoan** [comment]
> > I think I found it - inverter_limit_charge and discharge - just testing this now
> 
> This worked, had to set it to 5000 in yaml and it worked out to 7170 in the inverter.

I was going to say that, by default Predbat will do all charge/discharge at the max inverter rate.  Setting these in apps.yaml overwrites this behaviour.

It does sound like it could be an inverter issue if the givenergy app stops working.  Have you tried the BBC basic or Rubikcube Android app, do they stop as well?

**Comment by TheSargey** [comment]
Hi Geoffrey, no I've not tried those apps, hadn't heard of them until you
mentioned it.  I'll have a look into.

Cheers,

Luke

**Comment by gcoan** [comment]
Here's a link to the ios version of the BBC app https://apps.apple.com/app/id6443976497

**Comment by TheSargey** [comment]
Morning Geoff, hope you're well.

I'm setting up the ge_cloud as it seems that this is a more stable way of being able to monitor my inverter whilst I work on trying to get the local monitoring sorted (not sure how likely that will be in the near future).  

One thing I've noted is in the sensor setup, in the usual givtcp sensors there is inverter_mode which switches Eco on and off etc.  However this is missing from the givenergy_cloud.yaml - I think the most appropriate entity this would link to is switch.ge_inverter_{geserial}_enable_eco_mode but I assume it's been removed for a reason.  Should I just comment out inverter_mode whilst using the cloud?  Just wanted to make sure I'm setting it up correctly - potentially one for Trefor to clarify.

Cheers,

Sarge

**Comment by TheSargey** [comment]
Hmm - getting the following in predbat log:
2025-05-19 10:25:00.732545: Warn: Error downloading GE data from URL https://api.givenergy.cloud/v1/inverter/{my inverter serial}/data-points/2025-05-04?pageSize=4096
2025-05-19 10:25:00.771645: Info: record_status Warn: Error downloading GE data from cloud
2025-05-19 10:25:02.487263: Warn: Load mean is zero, unable to calculate divergence!

However, the entities for ge_cloud are all populating as expected.  Any idea how can I establish what the problem is here?

**Comment by TheSargey** [comment]
> Morning Geoff, hope you're well.
> 
> I'm setting up the ge_cloud as it seems that this is a more stable way of being able to monitor my inverter whilst I work on trying to get the local monitoring sorted (not sure how likely that will be in the near future).
> 
> One thing I've noted is in the sensor setup, in the usual givtcp sensors there is inverter_mode which switches Eco on and off etc. However this is missing from the givenergy_cloud.yaml - I think the most appropriate entity this would link to is switch.ge_inverter_{geserial}_enable_eco_mode but I assume it's been removed for a reason. Should I just comment out inverter_mode whilst using the cloud? Just wanted to make sure I'm setting it up correctly - potentially one for Trefor to clarify.
> 
> Cheers,
> 
> Sarge

I think I've found this - looks like the inverter mode is set by the inverter_type being 'GEC' under num_inverters.

**Comment by gcoan** [comment]
> I think I've found this - looks like the inverter mode is set by the inverter_type being 'GEC' under num_inverters.

it wouldn't surprise me if it does special things for the GE inverter types.  So is the template OK or need changing?

> Hmm - getting the following in predbat log:
> 2025-05-19 10:25:00.732545: Warn: Error downloading GE data from URL https://api.givenergy.cloud/v1/inverter/{my inverter serial}/data-points/2025-05-04?pageSize=4096
> 2025-05-19 10:25:00.771645: Info: record_status Warn: Error downloading GE data from cloud
> 2025-05-19 10:25:02.487263: Warn: Load mean is zero, unable to calculate divergence!

this sounds more serious.  If you look in the portal data, what do you see in the load column, is it populated properly?

if its not (and this is thus a givenergy issue) then a workaround would be to calculate the load yourself from a template sensor, example in the docs https://springfall2008.github.io/batpred/apps-yaml/#data-from-home-assistant but you'd have to wait for this to run for a while to build up history

**Comment by TheSargey** [comment]
Evening,

I dont think any changes are required on the template.

All of the data is populated appropriately in the load. Looking at the link that Predbat is trying to retrieve, it's giving a date of 2025-05-04 (I. E. May 4th), which makes me think it's trying to look back a couple of weeks from today to get load data (which makes sense as my apps.yaml looks at 7 and 14 days for historical data) but obviously I've only had the new inverter for a week so I'd assume it's failing as the cloud doesn't have data for my specific inverter going back that far. 

I'm going to set my apps.yaml to only look back 7 days and see if that clears the error.

Cheers,

Sarge

**Comment by gcoan** [comment]
yes predbat will try to load import data, load history, PV data, etc based upon days_previous

so if you don't have this history in either givtcp or the cloud then its not going to work well!

reducing days_previous should resolve this

**Comment by TheSargey** [comment]
> yes predbat will try to load import data, load history, PV data, etc based upon days_previous
> 
> so if you don't have this history in either givtcp or the cloud then its not going to work well!
> 
> reducing days_previous should resolve this

Exactly, changed it to 7 and the errors are gone. Thanks for being my sound board sir!

**Comment by TheSargey** [comment]
Hi @gcoan 

Im getting the cloud data error again, I've tried to shift the days previous around (even just setting it to 1) but it fires the following 

2025-05-21 00:27:47.032734: Info: record_status Warn: Error downloading GE data from cloud
2025-05-21 00:27:48.238438: Warn: Load mean is zero, unable to calculate divergence!

https://api.givenergy.cloud/v1/inverter/{geserial}/data-points/2025-05-21?pageSize=4096

Load data exists in the cloud, predbat was working happily until midnight which then triggered this error. Is it potentially to do with the link that predbat is trying to use to retrieve the historical data? Seems the switch from 2025-05-20 to -21 in the api call could be the culprit, what do you think? 

Inverter is online, ge cloud is up and populated. Not sure what's going on, I've tried the restart predbat etc but the load is not showing now in predbat. 

Curious!

**Comment by gcoan** [comment]
Its curious that it started reporting the error just after midnight.  I would avoid days_previous of 1 because that can cause weird results

Let's see if it happens again.

One option is to set a base load figure https://springfall2008.github.io/batpred/apps-yaml/#base-load which predbat will use if the load data is zero.  Not sure if this would fix this issue

**Comment by gcoan** [comment]
Interesting.  The inability to read load data early in the morning seems a givenergy portal/API bug, if the data isn't there for 8 hours then as you suspected, something must be delaying it on the portal end.

Was Predbat trying to retrieve today's data?

@springfall2008  Possibly predbat could be changed to only retrieve the historical data for the days_previous you require which could avoid the issue?

The failure to read charge date/time happens to me as well with givtcp.  Usually corresponds to a read error reported in the givtcp log. Predbat farts about the missing data, givtcp errors and restarts itself, and sometimes predbat has to intervene by restarting the givtcp addon.   But for me it's a transient issue and sorts itself out.  Unrelated I think

**Comment by TheSargey** [comment]
> 
> Was Predbat trying to retrieve today's data?
> 

Morning Geoff, it seems that Predbat (when it turns midnight) is trying to retrieve a data file using that current days date (i.e. this morning at the turn of midnight the following error posted):

2025-05-23 00:00:02.704955: Warn: Error downloading GE data from URL https://api.givenergy.cloud/v1/inverter/{geserial}/data-points/**2025-05-23**?pageSize=4096
2025-05-23 00:00:02.770747: Info: record_status Warn: Error downloading GE data from cloud
2025-05-23 00:00:06.121975: Warn: Load mean is zero, unable to calculate divergence!
2025-05-23 00:00:37.023710: Info: record_status Read-Only

This error then continously posts every five minutes in line with PredBats plan update policy.  I've still got the previous_days calculations set to 5,6,7 (not using 1).  As soon as 8am comes the following occurs:

2025-05-23 08:00:48.900804: Info: record_status Read-Only
2025-05-23 08:00:50.359651: Info: Refresh config entities due to their age of 480.0 minutes
2025-05-23 08:01:20.347058: Info: record_status Read-Only

Then the load data comes back into the Predbat plan.  The issue here is during the eight hour down time, the plan loses all of the load_kWh data - regardless of what days_previous is set.

As you've suggested, if Predbat can stop trying to retrieve the file using the current days date at midnight and instead continues to use the previous days date (i.e. for today it would use https://api.givenergy.cloud/v1/inverter/{geserial}/data-points/**2025-05-22**?pageSize=4096 until 8am) then potentially that would fix it.  

Cheers,

Luke

**Comment by gcoan** [comment]
> As you've suggested, if Predbat can stop trying to retrieve the file using the current days date at midnight and instead continues to use the previous days date (i.e. for today it would use https://api.givenergy.cloud/v1/inverter/{geserial}/data-points/**2025-05-22**?pageSize=4096 until 8am) then potentially that would fix it.

I think the solution is simpler than special coding around midnight, Predbat should be retrieving load data from the GE Cloud integration using days_previous

So just after midnight this morning (23/5/25), with your days_previous of 5, 6 and 7, Predbat should be trying to retrieve load data from 23-5 =18/5/25, 17/5/25 and 16/5/25, not starting from today's date (23/5/25) and working backwards.

I've changed the title to reflect this specific issue @springfall2008

**Comment by TheSargey** [comment]
Ok, thanks gentlemen.  Happy to help test when any updates are available.

**Comment by TheSargey** [comment]
Thanks Trefor, I've installed will report back tomorrow.

**Comment by TheSargey** [comment]
> Fix on main for testing

Morning - sadly after update still get the error:

2025-06-01 00:00:03.680334: Warn: Error downloading GE data from URL https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-01?pageSize=4096
2025-06-01 00:00:03.721956: Info: record_status Warn: Error downloading GE data from cloud
2025-06-01 00:00:08.464342: Warn: Load mean is zero, unable to calculate divergence!

As per last time, this goes until 8am when the file must become available.

**Comment by gcoan** [comment]
@springfall2008 I looked at the fix you did and didn't really understand it. It appeared to be suppressing errors to load history in the period after midnight and giving warnings when the data wasn't there. 

But my question remains, when days_previous is set to 5, 6 and 7, I can't see why predbat needs to retrieve history for today, shouldn't it be getting just the historical days needed ?

**Comment by springfall2008** [comment]
The reason it downloads all the data and not just the days previous is the load data is also used for cost calculations.

I've pushed another fix to 'main' for testing.

**Comment by TheSargey** [comment]
Thanks Trefor, I've updated, will let you know how it goes in the morning.

**Comment by TheSargey** [comment]
@springfall2008 Sadly issue still persists after main update. 

Just out of curiosity, is there no way to delay the retrieval of the latest file until after 8am GMT/BST?  I understand you need the load data but this is already correct and calculated in the plan based on the previous day file (i.e. it only goes to zero when it fails to retrieve the latest file at midnight, prior to this it has calculated load figures for the next day as expected).  I'm just thinking if you can somehow pause the retrieval of the gecloud data from midnight to 8am this would basically make the error go away. Then it would simply recalculate the load data when the new file is available at 8am?

Sorry, I wish I could help more but my Python skills aren't up to the task on this!

Thanks again for all your help and ongoing dev of Predbat!

**Comment by springfall2008** [comment]
Do you have a logfile with the error?

**Comment by springfall2008** [comment]
What is days_previous set to?

**Comment by TheSargey** [comment]
> Do you have a logfile with the error?

@springfall2008 Hi Trefor, yes I can provide. Do you want a file or just a text dump here?

> What is days_previous set to? 

days_previous currently set to 7

**Comment by springfall2008** [comment]
A copy of the logfile including the time around midnight would be good.

I don't see why missing data at midnight would impact 7 days ago

**Comment by springfall2008** [comment]
New fix released in .2 which might help

**Comment by TheSargey** [comment]
> New fix released in .2 which might help

Thanks @springfall2008, I've updated to main, will let you know how it goes this evening.  Here's a sample from predbat.log from the 15th at midnight when it tries to get the latest file from the cloud (note I'm running in read only at the moment whilst I'm working on the latest HV gen3 GE inverter):

----<snip>----
2025-06-15 00:00:00.458333: --------------- PredBat - update at 2025-06-15 00:00:00+01:00 with clock skew 0 minutes, minutes now 0
2025-06-15 00:00:00.462928: Saved current settings to /addon_configs/6adb4f0d_predbat/predbat_config.json
2025-06-15 00:00:00.466889: Using cached GITHub data for https://api.github.com/repos/springfall2008/batpred/releases age 45.0 minutes
2025-06-15 00:00:00.466988: Predbat /config/predbat.py version v8.20.15 currently running, latest version is v8.20.14 latest beta v8.20.14
2025-06-15 00:00:00.467156: Autoupdate: Currently on unknown version v8.20.15 (?)
2025-06-15 00:00:00.575146: Configuration: forecast_hours 48 num_cars 0 debug enable is False calculate_plan_every 10
2025-06-15 00:00:00.575550: Predbat mode is set to Control charge
2025-06-15 00:00:00.575622: NOTE: Read-only mode is enabled, the inverter controls will not be used!!
2025-06-15 00:00:01.212202: Fetching https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-07?pageSize=4096
2025-06-15 00:00:03.273064: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-08?pageSize=4096 age 460.0 minutes
2025-06-15 00:00:03.283665: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-09?pageSize=4096 age 460.0 minutes
2025-06-15 00:00:03.290086: Fetching https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-10?pageSize=4096
2025-06-15 00:00:04.481907: Fetching https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-11?pageSize=4096
2025-06-15 00:00:05.695994: Fetching https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-12?pageSize=4096
2025-06-15 00:00:06.333660: Fetching https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-13?pageSize=4096
2025-06-15 00:00:07.035372: Fetching https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-14?pageSize=4096
2025-06-15 00:00:07.490995: Fetching https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-15?pageSize=4096
2025-06-15 00:00:07.693975: Warn: Error downloading GE data from URL https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-15?pageSize=4096
2025-06-15 00:00:07.761993: Info: record_status Warn: Error downloading GE data from cloud
....
2025-06-15 00:00:09.974545: Warn: Load mean is zero, unable to calculate divergence!
2025-06-15 00:00:09.974666: Load divergence over 8.0 hours mean 0.0 W, min 0.0 W, max 0 W, std dev 0.0 W, divergence 0.0%
---<snip>---

If I go back five minutes before this to 23:55 this is what the log shows:

---<snip>---
2025-06-14 23:55:01.196598: --------------- PredBat - update at 2025-06-14 23:55:00+01:00 with clock skew 0 minutes, minutes now 1435
2025-06-14 23:55:01.197610: Saved current settings to /addon_configs/6adb4f0d_predbat/predbat_config.json
2025-06-14 23:55:01.211973: Using cached GITHub data for https://api.github.com/repos/springfall2008/batpred/releases age 40.0 minutes
2025-06-14 23:55:01.212164: Predbat /config/predbat.py version v8.20.15 currently running, latest version is v8.20.14 latest beta v8.20.14
2025-06-14 23:55:01.212300: Autoupdate: Currently on unknown version v8.20.15 (?)
2025-06-14 23:55:01.294191: Configuration: forecast_hours 48 num_cars 0 debug enable is False calculate_plan_every 10
2025-06-14 23:55:01.294616: Predbat mode is set to Control charge
2025-06-14 23:55:01.294685: NOTE: Read-only mode is enabled, the inverter controls will not be used!!
2025-06-14 23:55:01.660723: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-06?pageSize=4096 age 25.0 minutes
2025-06-14 23:55:01.663355: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-07?pageSize=4096 age 455.0 minutes
2025-06-14 23:55:01.665847: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-08?pageSize=4096 age 455.0 minutes
2025-06-14 23:55:01.671823: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-09?pageSize=4096 age 455.0 minutes
2025-06-14 23:55:01.675587: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-10?pageSize=4096 age 475.0 minutes
2025-06-14 23:55:01.679371: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-11?pageSize=4096 age 475.0 minutes
2025-06-14 23:55:01.683492: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-12?pageSize=4096 age 475.0 minutes
2025-06-14 23:55:01.687115: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-13?pageSize=4096 age 475.0 minutes
2025-06-14 23:55:01.689522: Return cached GE data for https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-14?pageSize=4096 age 475.0 minutes
2025-06-14 23:55:03.147283: Downloaded 12953 datapoints from GE going back 8 days
...
2025-06-14 23:55:05.924883: Load divergence over 8.0 hours mean 1287.5 W, min 0.0 W, max 3600.0 W, std dev 691.23 W, divergence 26.84%
---<snip>---

As discussed, when the clock turns midnight, Predbat is trying to download the latest datapoint file for the new day, however it would seem that GE don't generate this file until 8am in the morning as I'll see the "Info: record_status Warn: Error downloading GE data from cloud" until 8am at which point the error goes and Predbat resumes being able to calculate load correctly.

I've also noticed that Predbat seems to miss the load calculation, see here:

---<snip>---
2025-06-14 23:55:05.157996: PV Data for pv_forecast_today total 25.65 kWh
2025-06-14 23:55:05.158391: PV Data for pv_forecast_tomorrow total 19.25 kWh
2025-06-14 23:55:05.158498: PV Data for pv_forecast_d3 total 22.3 kWh
2025-06-14 23:55:05.158610: PV Data for pv_forecast_d4 total 24.97 kWh
2025-06-14 23:55:05.175905: PV Forecast for today is 25.65 (18.64 10% 28.03 90%) kWh and left today is 0.0 (0.0 10% 0.0 90%) kWh
2025-06-14 23:55:05.289062: PV Forecast for day tomorrow is 19.25 (9.99 10% 26.31 90%) kWh
2025-06-14 23:55:05.325568: PV Forecast for day d2 is 22.3 (15.85 10% 26.44 90%) kWh
2025-06-14 23:55:05.397663: PV Forecast for day d3 is 24.97 (13.01 10% 26.48 90%) kWh
**2025-06-14 23:55:05.537286: Historical data totals for days [7] are [54.92] - min 54.92
2025-06-14 23:55:05.538406: Historical days now [7] weight [1]
2025-06-14 23:55:05.574652: Today's load divergence 116.76 % in-day adjustment 115.92 % damping 0.95x
2025-06-14 23:55:05.574798: Today's predicted so far 27.03 kWh with 3.7 kWh car/iBoost excluded and 17.19 kWh import ignored and 0 forecast extra.
2025-06-14 23:55:05.574842: Today's actual load so far 32.49 kWh with 3.08 kWh Car/iBoost excluded and 4.57 kWh import ignored.**
2025-06-14 23:55:05.808408: Inverter 0: Type GEC GivEnergy Cloud
---<snip>---

However, after midnight it shows:
---<snip>---
2025-06-15 00:00:09.504941: PV Data for pv_forecast_today total 19.25 kWh
2025-06-15 00:00:09.505349: PV Data for pv_forecast_tomorrow total 22.3 kWh
2025-06-15 00:00:09.505533: PV Data for pv_forecast_d3 total 24.97 kWh
2025-06-15 00:00:09.505648: PV Data for pv_forecast_d4 total 21.57 kWh
2025-06-15 00:00:09.547605: PV Forecast for today is 19.25 (9.99 10% 26.31 90%) kWh and left today is 19.25 (9.99 10% 26.31 90%) kWh
2025-06-15 00:00:09.626121: PV Forecast for day tomorrow is 22.3 (15.85 10% 26.44 90%) kWh
2025-06-15 00:00:09.668866: PV Forecast for day d2 is 24.97 (13.01 10% 26.48 90%) kWh
2025-06-15 00:00:09.704875: PV Forecast for day d3 is 21.57 (11.74 10% 26.8 90%) kWh
2025-06-15 00:00:09.821881: Inverter 0: Type GEC GivEnergy Cloud
---<snip>---

So it seems to ignore the historical load calculation completely when it errors on the file download.

Is this enough info from the logfile or do you want to see more?

Cheers,

Sarge

**Comment by TheSargey** [comment]
@springfall2008  Sadly same issue as before in latest update:

2025-06-17 00:00:01.459412: Fetching https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-17?pageSize=4096
2025-06-17 00:00:02.756168: Warn: Error downloading GE data from URL https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-17?pageSize=4096

All of the load kWh in the plan goes to zero.  At 8am the file will become available and Predbat will start to work out the load correctly again.

![Image](https://github.com/user-attachments/assets/ea87fafd-1f49-4318-8cb5-1328faadd8af)

**Comment by TheSargey** [comment]
@springfall2008 Morning - data was a little later today, seems the file wasn't available until 08:15

--<Snip>--
2025-06-17 08:15:00.590908: Warn: Error downloading GE data from URL https://api.givenergy.cloud/v1/inverter/{ge_serial}/data-points/2025-06-17?pageSize=4096
2025-06-17 08:15:00.607269: Info: record_status Warn: Error downloading GE data from cloud
2025-06-17 08:15:07.916496: Warn: Load mean is zero, unable to calculate divergence!
2025-06-17 08:15:13.933079: Info: record_status Read-Only
2025-06-17 08:22:09.641197: Info: record_status Read-Only
2025-06-17 08:22:11.227238: Info: Refresh config entities due to their age of 480.0 minutes
2025-06-17 08:24:06.089853: Info: record_status Read-Only
--<Snip>--

Load is back now and Predbat running as expected:

![Image](https://github.com/user-attachments/assets/faa85ecf-a82b-424d-8df9-94cb03dba8d0)


I randomly get this error in my logs during the day, however I don't think it has anything to do with the issue at hand:

--<Snip>--
2025-06-17 08:30:14.142214: Error: Inverter 0 unable to read charge window time as charge_start_time or charge_end_time is None
2025-06-17 08:30:14.157138: Warn: record_status Error: Inverter 0 unable to read charge window time as charge_start_time or charge_end_time is None
2025-06-17 08:30:14.157754: Error: Exception raised 
2025-06-17 08:30:14.302670: Error: Traceback (most recent call last):
  File "/config/predbat.py", line 1429, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/predbat.py", line 645, in update_pred
    self.fetch_inverter_data()
  File "/config/execute.py", line 649, in fetch_inverter_data
    inverter.update_status(self.minutes_now)
  File "/config/inverter.py", line 938, in update_status
    raise ValueError
ValueError
2025-06-17 08:30:14.318524: Info: record_status Error: Exception raised 
2025-06-17 08:30:14.319086: Error: 
Traceback (most recent call last):
  File "/config/hass.py", line 191, in timer_tick
    item["callback"](None)
  File "/config/predbat.py", line 1434, in run_time_loop
    raise e
  File "/config/predbat.py", line 1429, in run_time_loop
    self.update_pred(scheduled=True)
  File "/config/predbat.py", line 645, in update_pred
    self.fetch_inverter_data()
  File "/config/execute.py", line 649, in fetch_inverter_data
    inverter.update_status(self.minutes_now)
  File "/config/inverter.py", line 938, in update_status
    raise ValueError
ValueError
--<Snip>--

Must be an issue where Predbat is unable to derive the charge window time from the cloud.  I'll raise it separately in due course.

Cheers,

Sarge

**Comment by springfall2008** [comment]
New fix for the GE CLoud midnight issue: https://github.com/springfall2008/batpred/releases/tag/v8.22.0

**Comment by TheSargey** [comment]
> New fix for the GE CLoud midnight issue: https://github.com/springfall2008/batpred/releases/tag/v8.22.0

Thanks as always @springfall2008 - will report back in the morning.

Cheers,

Sarge

**Comment by TheSargey** [comment]
> New fix for the GE CLoud midnight issue: https://github.com/springfall2008/batpred/releases/tag/v8.22.0

@springfall2008 You sir, are a legend. Working perfectly now. As per logs "2025-07-04 01:20:00.516143: Info: No GE Cloud data available for today yet, continuing" and I verified that the load data remained consistent and correct with the previous day. 

Interestingly, the cloud data availibilty message stopped at about 01:20 last night when usually the previous load error before patch would stop around 8am. Not sure whether they're releasing the file earlier now or Predbat stops generating the response.

Anyway, all working, I'm a very happy camper. I'll be buying you a beer for sure!

Cheers,

Sarge
