### ISSUE TITLE
PV Forecast differs from solcast and pv scaling has no effect

### ISSUE THREAD

**Issue by raldred** [springfall2008/batpred#2445]
**Describe the bug**
Solcast has been predicting much higher forecasts than I've been seeing the last few days.
In looking into this I have noticed that predbat's PV forecast is higher than what solcast has itself.
I have tried to use `predbat_pv_scaling`, dropping it right down to see if that can adjust what predbat sees but it doesn't appear to change anything.

**Expected behaviour**
Predbat shouldn't be showing pv forcast above what solcast has, it should also reduce pv forecast adjusting using pv scaling

**Predbat version**
v8.20.14

**Environment details**

- Luxpower
- Standard HAOS installer
- Predbat addon

**Screenshots**
If applicable, add screenshots to help explain your problem. The most useful ones can be your battery chart, the Predbat HTML plan and your current settings in HA.

![Image](https://github.com/user-attachments/assets/65d6036f-00c4-444d-a99d-c0cae933fec3)
![Image](https://github.com/user-attachments/assets/deac6778-0d9c-4462-8615-0cb4006aea2b)

**Log file**

[predbat.log](https://github.com/user-attachments/files/20676596/predbat.log)

**Comment by johnwb87** [comment]
`Warn: PV Forecast data adds up to 352.28 kWh but total sensors add up to 219.60000000000002 kWh, this is unexpected and hence data maybe misleading (factor 1.6)`

That's interesting. Also the preceding lines show that predbat is seeing the sensor correctly. I think it suggests that there is something going on with the detailed forecast. That is what predbat uses to build the 30 min solar forecast.

**Comment by springfall2008** [comment]
I'd need to see what's in detailedforecast to compare this against the total in the sensor, this is what its saying is mismatched.

**Comment by springfall2008** [comment]
I may have found the issue here, if the future days are not fully populated then this scaling goes wrong, I've pushed a fix to main for testing and will release it in the next full release

**Comment by raldred** [comment]
I've switched to main, warning is still present and PV forecast is still showing more than solcast 

The warning shows...
```
18264	2025-06-15 21:20:04.138005: Warn: PV Forecast today adds up to 78.05 kWh but total sensors add up to 54.6 kWh, this is unexpected and hence data maybe misleading (factor 1.4)
18314	2025-06-15 21:20:05.915070: PV: [ 36.6, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.61, 36.66, 36.77, 37.02, 37.5, 38.3, 39.6, 41.47, 43.93, 46.91, 50.35, 54.12, 58.03, 62.02, 66.06, 70.11, 74.09, 77.95, 81.63, 85.08, 88.23, 91.04, 93.46, 95.48, 97.09, 98.28, 99.03, 99.61, 100.04, 100.32, 100.53, 100.69, 100.79, 100.83, 100.83, 100.83, 100.83, 100.83, 100.83]
18281	2025-06-15 21:20:05.645235: PV Forecast for day d3 is 75.23 (43.2 10% 82.7 90% 75.23 CL) kWh
18280	2025-06-15 21:20:05.637850: PV Forecast for day d2 is 45.95 (9.37 10% 78.41 90% 31.46 CL) kWh
18279	2025-06-15 21:20:05.630675: PV Forecast for day tomorrow is 64.22 (41.79 10% 80.47 90% 43.96 CL) kWh
18278	2025-06-15 21:20:05.612892: PV Forecast for today is 55.75 (26.56 10% 78.01 90% 38.11 calib) kWh and left today is 0.02 (0.01 10% 0.03 90% 0.01 calib) kWh
18277	2025-06-15 21:20:05.592496: PV Calibration: PV production: 73.14 kWh, Total forecast: 105.81 kWh adjustment 0.6912x slot adjustments {0: 1.0, 30: 1.0, 60: 1.0, 90: 1.0, 120: 1.0, 150: 1.0, 180: 1.0, 210: 1.0, 240: 1.0, 270: 1.0, 300: 1.0, 330: 1.0, 360: 1.0, 390: 0.9672, 420: 0.9293, 450: 0.996, 480: 1.0654, 510: 0.7789, 540: 0.9391, 570: 0.8116, 600: 1.0493, 630: 1.126, 660: 1.1472, 690: 0.9585, 720: 0.6998, 750: 0.8639, 780: 1.1532, 810: 1.0594, 840: 1.0678, 870: 1.039, 900: 0.9467, 930: 0.9089, 960: 1.0785, 990: 1.1605, 1020: 1.0843, 1050: 1.0368, 1080: 0.9866, 1110: 1.0619, 1140: 1.0, 1170: 1.0, 1200: 1.0, 1230: 1.0, 1260: 1.0, 1290: 1.0, 1320: 1.0, 1350: 1.0, 1380: 1.0, 1410: 1.0}
18276	2025-06-15 21:20:05.592192: PV Calibration: Worst day scaling factor 0.57 best day scaling factor 1.5
18275	2025-06-15 21:20:05.592159: PV Calibration: Past day 1 had 45.87 kWh of PV forecast data and actual 71.61 kWh
18274	2025-06-15 21:20:05.592123: PV Calibration: Past day 2 had 65.26 kWh of PV forecast data and actual 41.73 kWh
18273	2025-06-15 21:20:05.592065: PV Calibration: Past day 3 had 42.45 kWh of PV forecast data and actual 30.0 kWh
18272	2025-06-15 21:20:05.592028: PV Calibration: Past day 4 had 72.27 kWh of PV forecast data and actual 60.01 kWh
18271	2025-06-15 21:20:05.591992: PV Calibration: Past day 5 had 58.44 kWh of PV forecast data and actual 40.81 kWh
18270	2025-06-15 21:20:05.591950: PV Calibration: Past day 6 had 38.2 kWh of PV forecast data and actual 29.22 kWh
18269	2025-06-15 21:20:05.591907: PV Calibration: Past day 7 had 52.93 kWh of PV forecast data and actual 30.06 kWh
18268	2025-06-15 21:20:05.591870: PV Calibration: Past day 8 had 40.83 kWh of PV forecast data and actual 23.28 kWh
18267	2025-06-15 21:20:05.591831: PV Calibration: Past day 9 had 59.91 kWh of PV forecast data and actual 38.84 kWh
18266	2025-06-15 21:20:05.591725: PV Calibration: Past day 10 had 0.01 kWh of PV forecast data and actual 0.13 kWh
18265	2025-06-15 21:20:04.161550: PV Calibration: Fetching PV data for calibration
18264	2025-06-15 21:20:04.138005: Warn: PV Forecast today adds up to 78.05 kWh but total sensors add up to 54.6 kWh, this is unexpected and hence data maybe misleading (factor 1.4)
18263	2025-06-15 21:20:04.137962: PV Data for pv_forecast_d4 total 57.89 kWh

```

![Image](https://github.com/user-attachments/assets/7ce89f46-b1d9-4f25-8ce2-4e655b13d502)

Here's detailedForecast from the solcast sensor

```
[{'period_start': datetime.datetime(2025, 6, 15, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 0, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 1, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 1, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 2, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 2, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 3, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 3, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 4, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 4, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0043, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0043}, {'period_start': datetime.datetime(2025, 6, 15, 5, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0522, 'pv_estimate10': 0.0218, 'pv_estimate90': 0.0827}, {'period_start': datetime.datetime(2025, 6, 15, 5, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.1262, 'pv_estimate10': 0.0477, 'pv_estimate90': 0.4048}, {'period_start': datetime.datetime(2025, 6, 15, 6, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.2557, 'pv_estimate10': 0.0859, 'pv_estimate90': 1.1886}, {'period_start': datetime.datetime(2025, 6, 15, 6, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.5424, 'pv_estimate10': 0.1246, 'pv_estimate90': 2.0486}, {'period_start': datetime.datetime(2025, 6, 15, 7, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.8593, 'pv_estimate10': 0.1633, 'pv_estimate90': 2.9073}, {'period_start': datetime.datetime(2025, 6, 15, 7, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 1.2482, 'pv_estimate10': 0.221, 'pv_estimate90': 3.6368}, {'period_start': datetime.datetime(2025, 6, 15, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 3.4889, 'pv_estimate10': 2.75, 'pv_estimate90': 4.0988}, {'period_start': datetime.datetime(2025, 6, 15, 8, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 3.2367, 'pv_estimate10': 2.0467, 'pv_estimate90': 4.9354}, {'period_start': datetime.datetime(2025, 6, 15, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 3.6068, 'pv_estimate10': 2.0257, 'pv_estimate90': 5.1045}, {'period_start': datetime.datetime(2025, 6, 15, 9, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 4.9228, 'pv_estimate10': 2.5842, 'pv_estimate90': 6.0644}, {'period_start': datetime.datetime(2025, 6, 15, 10, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 5.2635, 'pv_estimate10': 2.7577, 'pv_estimate90': 6.4348}, {'period_start': datetime.datetime(2025, 6, 15, 10, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 5.5122, 'pv_estimate10': 2.5442, 'pv_estimate90': 6.6571}, {'period_start': datetime.datetime(2025, 6, 15, 11, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 5.6943, 'pv_estimate10': 2.4517, 'pv_estimate90': 6.7933}, {'period_start': datetime.datetime(2025, 6, 15, 11, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 5.421, 'pv_estimate10': 4.713, 'pv_estimate90': 6.0278}, {'period_start': datetime.datetime(2025, 6, 15, 12, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 5.5278, 'pv_estimate10': 3.9173, 'pv_estimate90': 6.3467}, {'period_start': datetime.datetime(2025, 6, 15, 12, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 5.1647, 'pv_estimate10': 2.7306, 'pv_estimate90': 6.5926}, {'period_start': datetime.datetime(2025, 6, 15, 13, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 4.5188, 'pv_estimate10': 1.873, 'pv_estimate90': 6.2443}, {'period_start': datetime.datetime(2025, 6, 15, 13, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 3.6092, 'pv_estimate10': 0.7458, 'pv_estimate90': 5.6278}, {'period_start': datetime.datetime(2025, 6, 15, 14, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 3.0354, 'pv_estimate10': 0.2008, 'pv_estimate90': 5.1918}, {'period_start': datetime.datetime(2025, 6, 15, 14, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 2.824, 'pv_estimate10': 0.1379, 'pv_estimate90': 4.7201}, {'period_start': datetime.datetime(2025, 6, 15, 15, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 1.6447, 'pv_estimate10': 1.289, 'pv_estimate90': 1.972}, {'period_start': datetime.datetime(2025, 6, 15, 15, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 1.7889, 'pv_estimate10': 0.788, 'pv_estimate90': 2.7096}, {'period_start': datetime.datetime(2025, 6, 15, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 2.0591, 'pv_estimate10': 0.9945, 'pv_estimate90': 2.8338}, {'period_start': datetime.datetime(2025, 6, 15, 16, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 1.9625, 'pv_estimate10': 0.7586, 'pv_estimate90': 2.5381}, {'period_start': datetime.datetime(2025, 6, 15, 17, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 1.6524, 'pv_estimate10': 0.443, 'pv_estimate90': 2.0682}, {'period_start': datetime.datetime(2025, 6, 15, 17, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 1.1359, 'pv_estimate10': 0.1597, 'pv_estimate90': 1.7183}, {'period_start': datetime.datetime(2025, 6, 15, 18, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.874, 'pv_estimate10': 0.1135, 'pv_estimate90': 1.4284}, {'period_start': datetime.datetime(2025, 6, 15, 18, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.7007, 'pv_estimate10': 0.1135, 'pv_estimate90': 1.1275}, {'period_start': datetime.datetime(2025, 6, 15, 19, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.5513, 'pv_estimate10': 0.1261, 'pv_estimate90': 0.8018}, {'period_start': datetime.datetime(2025, 6, 15, 19, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.3989, 'pv_estimate10': 0.1177, 'pv_estimate90': 0.4673}, {'period_start': datetime.datetime(2025, 6, 15, 20, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.2125, 'pv_estimate10': 0.0766, 'pv_estimate90': 0.2339}, {'period_start': datetime.datetime(2025, 6, 15, 20, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.119, 'pv_estimate10': 0.0424, 'pv_estimate90': 0.1418}, {'period_start': datetime.datetime(2025, 6, 15, 21, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0383, 'pv_estimate10': 0.0128, 'pv_estimate90': 0.0541}, {'period_start': datetime.datetime(2025, 6, 15, 21, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 22, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 22, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 23, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}, {'period_start': datetime.datetime(2025, 6, 15, 23, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')), 'pv_estimate': 0.0, 'pv_estimate10': 0.0, 'pv_estimate90': 0.0}]
```

**Comment by springfall2008** [comment]
So the data you posted adds up to 78.0526 but it doesn't match the sensor value which is 54.

Something is wrong with your Solcast setup as the data is bogus.

You can even see it on the card itself, it has the estimate for the two roof aspects but the total isn't the two combined.

I'm wondering if you have an AC Limit set in the Solcast web site that is causing it to clip the data here? If so I'd set it to something large like 99 and retry?

**Comment by chalfontchubby** [comment]
Closing since there has been no response to the last request for a while. Please open another ticket if there is still a problem.
