### ISSUE TITLE
Plan is showing incorrect Octopus Agile rates (Predbat Octopus Direct)

### ISSUE THREAD

**Issue by brickatius** [springfall2008/batpred#2867]
**Describe the bug**
Switched from Octopus Flux to Agile Import/Outgoing Octopus a few days ago. Every day since, the Predbat plan is showing an incorrect Octopus Agile  import rate of 0.00 for the 23:00 & 23:30 slots. This is causing the plan to implement a one hour charge slot at these times thereby possibly skewing what might have happened earlier in the day. Obviously, as a result of this the cost figures are inaccurate too.  

**Expected behaviour**
The plan should show the correct rate for these time slots.

**Predbat version**

8.27.4 using the direct connection to Octopus

**Environment details**

- LuxPower
- Standard HAOS installer Core 2025.11.0
- OS 16.3

**Log file**
Nothing in the log file
**Predbat debug yaml file**

[predbat_debug-4.yaml.txt](https://github.com/user-attachments/files/23386989/predbat_debug-4.yaml.txt)

**The incorrect 0:00 rates as shown in the plan.**

![Image](https://github.com/user-attachments/assets/3b703045-1707-4b6a-a1f5-d752ba9d3530)
**Some rates however are shown in the Compare feature (although they are not what they should be according to the Octopus Agile website, even though the rest of the day is correct). Running 'compare now' then shows 0:00 rates for the 23:00 and 23:30 time slots.**

![Image](https://github.com/user-attachments/assets/87fecafc-9152-4f96-9838-5e10afa051c4)
**Reverting to an earlier version (8.26.4) fixes the issue of the 0:00 slots but the figures shown are again not what they should be.**

![Image](https://github.com/user-attachments/assets/f371ef29-0705-44a6-9cff-90e4f82aec5c)

**Interesting note:** It is now just past 4PM, the Octopus rates for tomorrow have been released and the 0:00 rate 23:00 and 23:30 slots have now been filled with the correct rates. 

**This last image shows a plan generated post 4PM with all of the rates shown and in accord with the Octopus Agile website.**

![Image](https://github.com/user-attachments/assets/211405b3-ecdb-4209-8b3d-2ef4258fa4dd)

**Comment by gcoan** [comment]
it might be worth seeing if you get the same problem with the Octopus integration?   I suspect you won't and its a bug with Predbat Octopus direct, but would be useful to confirm

**Comment by brickatius** [comment]
I can confirm that the bug is only with the direct connection. 
I swapped over to the Octopus integration and all the rates are consistent with the Agile website for my region. 
(The 23:00 & 23:30 slots were at 0:00 again this morning, having been correct after 4PM yesterday. I’m sorry but I’ve no idea what time they went wrong again. Presumably some time after midnight.)

**Comment by brickatius** [comment]
I don't know if this is relevant. I see that any rates after the 22:30 slot today are followed by a ? (obviously because the real rates haven't been released yet) and these ? rates are the same as the equivalent slot 24 hours earlier. Could the issue be somehow related to the data that is used for the Compare feature, given that that runs for 24 hours from midnight?

**Comment by gcoan** [comment]
> I don't know if this is relevant. I see that any rates after the 22:30 slot today are followed by a ? (obviously because the real rates haven't been released yet) and these ? rates are the same as the equivalent slot 24 hours earlier. Could the issue be somehow related to the data that is used for the Compare feature, given that that runs for 24 hours from midnight?

No that's not relevant, its normal predbat behaviour.

If any rates that the plan needs are not available then predbat repeats the prior day rates and adds a question mark

You can get a more accurate prediction of what the future rates from 10pm will be by using the norddata prediction that's available from about 10am.  Setup details in the apps.yaml documentation

**Comment by brickatius** [comment]
Thank you!

**Comment by brickatius** [comment]
Fixed in Predbat v8.27.9

**Comment by brickatius** [comment]
I wrongly thought this was fixed in v8.27.11.

**Comment by WhatIsThisAllAboutSilly** [comment]
This is not fixed and I'm **not** using predbat octopus direct but using the Octopus Integration.

Export shows non-zero values, import shows 0.0pence.

Edit: Using Version v8.31.0

Edit 2: Let me know what info is needed to try and Debug this.

**Comment by gcoan** [comment]
> Edit 2: Let me know what info is needed to try and Debug this.

please include a copy of the plan, your apps.yaml configuration, and the predbat log file.

It would also help if you can show what is in the Octopus energy rates.  Yours sounds like a different problem, or a configuration issue

**Comment by WhatIsThisAllAboutSilly** [comment]
Just had the next days rates update, and all the slots now correctly either show the true rates or the estimated rates (i.e. ?). I think this bug only occurs after midnight, so it doesn't have the next day rates anymore.

**Comment by WhatIsThisAllAboutSilly** [comment]
Ok it has done it again now after a refresh.

[config.yaml](https://github.com/user-attachments/files/24389002/config.yaml)

<img width="796" height="782" alt="Image" src="https://github.com/user-attachments/assets/13a32f64-b235-45a1-9cbd-ccfcd795e50a" />

Predbat log won't upload, is there an email I can send it to?

Rates look fine... Here are the rates...

`event_types:
  - octopus_energy_electricity_current_day_rates
event_type: octopus_energy_electricity_current_day_rates
rates:
  - start: "2025-12-31T00:00:00+00:00"
    end: "2025-12-31T00:30:00+00:00"
    value_inc_vat: 0.0808
    is_capped: false
  - start: "2025-12-31T00:30:00+00:00"
    end: "2025-12-31T01:00:00+00:00"
    value_inc_vat: 0.0862
    is_capped: false
  - start: "2025-12-31T01:00:00+00:00"
    end: "2025-12-31T01:30:00+00:00"
    value_inc_vat: 0.082
    is_capped: false
  - start: "2025-12-31T01:30:00+00:00"
    end: "2025-12-31T02:00:00+00:00"
    value_inc_vat: 0.0775
    is_capped: false
  - start: "2025-12-31T02:00:00+00:00"
    end: "2025-12-31T02:30:00+00:00"
    value_inc_vat: 0.0763
    is_capped: false
  - start: "2025-12-31T02:30:00+00:00"
    end: "2025-12-31T03:00:00+00:00"
    value_inc_vat: 0.0716
    is_capped: false
  - start: "2025-12-31T03:00:00+00:00"
    end: "2025-12-31T03:30:00+00:00"
    value_inc_vat: 0.0716
    is_capped: false
  - start: "2025-12-31T03:30:00+00:00"
    end: "2025-12-31T04:00:00+00:00"
    value_inc_vat: 0.0716
    is_capped: false
  - start: "2025-12-31T04:00:00+00:00"
    end: "2025-12-31T04:30:00+00:00"
    value_inc_vat: 0.0735
    is_capped: false
  - start: "2025-12-31T04:30:00+00:00"
    end: "2025-12-31T05:00:00+00:00"
    value_inc_vat: 0.0716
    is_capped: false
  - start: "2025-12-31T05:00:00+00:00"
    end: "2025-12-31T05:30:00+00:00"
    value_inc_vat: 0.0763
    is_capped: false
  - start: "2025-12-31T05:30:00+00:00"
    end: "2025-12-31T06:00:00+00:00"
    value_inc_vat: 0.0754
    is_capped: false
  - start: "2025-12-31T06:00:00+00:00"
    end: "2025-12-31T06:30:00+00:00"
    value_inc_vat: 0.082
    is_capped: false
  - start: "2025-12-31T06:30:00+00:00"
    end: "2025-12-31T07:00:00+00:00"
    value_inc_vat: 0.0829
    is_capped: false
  - start: "2025-12-31T07:00:00+00:00"
    end: "2025-12-31T07:30:00+00:00"
    value_inc_vat: 0.081
    is_capped: false
  - start: "2025-12-31T07:30:00+00:00"
    end: "2025-12-31T08:00:00+00:00"
    value_inc_vat: 0.0887
    is_capped: false
  - start: "2025-12-31T08:00:00+00:00"
    end: "2025-12-31T08:30:00+00:00"
    value_inc_vat: 0.0875
    is_capped: false
  - start: "2025-12-31T08:30:00+00:00"
    end: "2025-12-31T09:00:00+00:00"
    value_inc_vat: 0.0942
    is_capped: false
  - start: "2025-12-31T09:00:00+00:00"
    end: "2025-12-31T09:30:00+00:00"
    value_inc_vat: 0.0904
    is_capped: false
  - start: "2025-12-31T09:30:00+00:00"
    end: "2025-12-31T10:00:00+00:00"
    value_inc_vat: 0.0902
    is_capped: false
  - start: "2025-12-31T10:00:00+00:00"
    end: "2025-12-31T10:30:00+00:00"
    value_inc_vat: 0.0914
    is_capped: false
  - start: "2025-12-31T10:30:00+00:00"
    end: "2025-12-31T11:00:00+00:00"
    value_inc_vat: 0.0885
    is_capped: false
  - start: "2025-12-31T11:00:00+00:00"
    end: "2025-12-31T11:30:00+00:00"
    value_inc_vat: 0.0816
    is_capped: false
  - start: "2025-12-31T11:30:00+00:00"
    end: "2025-12-31T12:00:00+00:00"
    value_inc_vat: 0.0805
    is_capped: false
  - start: "2025-12-31T12:00:00+00:00"
    end: "2025-12-31T12:30:00+00:00"
    value_inc_vat: 0.0795
    is_capped: false
  - start: "2025-12-31T12:30:00+00:00"
    end: "2025-12-31T13:00:00+00:00"
    value_inc_vat: 0.0804
    is_capped: false
  - start: "2025-12-31T13:00:00+00:00"
    end: "2025-12-31T13:30:00+00:00"
    value_inc_vat: 0.0832
    is_capped: false
  - start: "2025-12-31T13:30:00+00:00"
    end: "2025-12-31T14:00:00+00:00"
    value_inc_vat: 0.0827
    is_capped: false
  - start: "2025-12-31T14:00:00+00:00"
    end: "2025-12-31T14:30:00+00:00"
    value_inc_vat: 0.082
    is_capped: false
  - start: "2025-12-31T14:30:00+00:00"
    end: "2025-12-31T15:00:00+00:00"
    value_inc_vat: 0.0855
    is_capped: false
  - start: "2025-12-31T15:00:00+00:00"
    end: "2025-12-31T15:30:00+00:00"
    value_inc_vat: 0.0914
    is_capped: false
  - start: "2025-12-31T15:30:00+00:00"
    end: "2025-12-31T16:00:00+00:00"
    value_inc_vat: 0.0998
    is_capped: false
  - start: "2025-12-31T16:00:00+00:00"
    end: "2025-12-31T16:30:00+00:00"
    value_inc_vat: 0.1589
    is_capped: false
  - start: "2025-12-31T16:30:00+00:00"
    end: "2025-12-31T17:00:00+00:00"
    value_inc_vat: 0.1615
    is_capped: false
  - start: "2025-12-31T17:00:00+00:00"
    end: "2025-12-31T17:30:00+00:00"
    value_inc_vat: 0.162
    is_capped: false
  - start: "2025-12-31T17:30:00+00:00"
    end: "2025-12-31T18:00:00+00:00"
    value_inc_vat: 0.162
    is_capped: false
  - start: "2025-12-31T18:00:00+00:00"
    end: "2025-12-31T18:30:00+00:00"
    value_inc_vat: 0.1588
    is_capped: false
  - start: "2025-12-31T18:30:00+00:00"
    end: "2025-12-31T19:00:00+00:00"
    value_inc_vat: 0.1516
    is_capped: false
  - start: "2025-12-31T19:00:00+00:00"
    end: "2025-12-31T19:30:00+00:00"
    value_inc_vat: 0.081
    is_capped: false
  - start: "2025-12-31T19:30:00+00:00"
    end: "2025-12-31T20:00:00+00:00"
    value_inc_vat: 0.0857
    is_capped: false
  - start: "2025-12-31T20:00:00+00:00"
    end: "2025-12-31T20:30:00+00:00"
    value_inc_vat: 0.081
    is_capped: false
  - start: "2025-12-31T20:30:00+00:00"
    end: "2025-12-31T21:00:00+00:00"
    value_inc_vat: 0.0768
    is_capped: false
  - start: "2025-12-31T21:00:00+00:00"
    end: "2025-12-31T21:30:00+00:00"
    value_inc_vat: 0.081
    is_capped: false
  - start: "2025-12-31T21:30:00+00:00"
    end: "2025-12-31T22:00:00+00:00"
    value_inc_vat: 0.0766
    is_capped: false
  - start: "2025-12-31T22:00:00+00:00"
    end: "2025-12-31T22:30:00+00:00"
    value_inc_vat: 0.0773
    is_capped: false
  - start: "2025-12-31T22:30:00+00:00"
    end: "2025-12-31T23:00:00+00:00"
    value_inc_vat: 0.0627
    is_capped: false
min_rate: 0.0627
max_rate: 0.162
average_rate: 0.09162391
mpan: "XXXXX"
serial_number: XXXXXX
tariff_code: E-1R-AGILE-OUTGOING-19-05-13-E
friendly_name: Current Day Rates Export Electricity (XXXX/XXXXXX)




event_types:
  - octopus_energy_electricity_next_day_rates
event_type: octopus_energy_electricity_next_day_rates
rates: []
min_rate: null
max_rate: null
average_rate: 1
mpan: "XXXXX"
serial_number: XXXXXX
tariff_code: E-1R-AGILE-OUTGOING-19-05-13-E
friendly_name: Current Day Rates Export Electricity (XXXX/XXXXXX)





`

**Comment by gcoan** [comment]
the current day rates look fine, and they only go up to 22:30.  The issue is in the handling of the previous day rates which will have the 23:00 and 23:30 prices from Tuesday which Predbat should be replicating into the Wednesday rates

**Comment by WhatIsThisAllAboutSilly** [comment]
Agreed, it looks like predbat should be taking two days ago rates to fill in 23:00 and 23:30.

Should be an easier fix?

Or perhaps we could add something that looks at something like agilepredict?
