### ISSUE TITLE
Fox Cloud forced export fails

### ISSUE THREAD

**Issue by davidjwood** [springfall2008/batpred#3063]
**Describe the bug**
Forced exports usually fail on my Fox Cloud inverter.

The log extract below shows multiple issues, the first of which is probably the root cause:
- The discharge target percentage is calculated at 10.0, when it should be 17.51 / 23.04 = 76.0 rounded to the nearest 1.0. This ultimately causes Fox Cloud to return a 40257 error code, presumably because fdSoc < minSocOnGrid for the export slot
- fdPwr for the export slot is formatted without a trailing .0 - this is probably just a cosmetic bug, but could conceivably lead to a Fox Cloud error code, and 
- fdPwr for the export slot is set to 6000, when this should arguably be clamped to the configured export limit on the inverter (5000.0; I am G99 limited to 5kW export).

**Expected behaviour**
Forced exports should work!

**Predbat version**

v8.29.11

**Environment details**

- Fox ESS H1-6.0-E-G2 with WLan-WW module and two EP12 Plus batteries (23.04 kWh combined capacity), cloud connection to Predbat
- HAOS 16.3 running Home Assistant 2025.12.3 on an x64 virtual machine

**Log file (extract, inverter SN masked)**

The full masked log file is in [predbat.log](https://github.com/user-attachments/files/24148672/predbat.Fox.Inverter.SN.masked.log)

>2025-12-14 03:55:14.931462: Include original export start 12-14 03:55:00 with our start which is 12-14 03:55:00 (charge start 12-16 00:00:00 end 12-16 00:00:00)
2025-12-14 03:55:14.931608: Next export window will be: 2025-12-14 03:55:00+00:00 - 2025-12-14 04:30:00+00:00 at reserve 76.0
2025-12-14 03:55:14.931715: Exporting now - current SoC 20.736kWh and target 17.51kWh and power adjust 1.0
2025-12-14 03:55:14.932052: Inverter 0 Adjust force export to True, change times from 03:55:00 - 04:30:00 to 03:55:00 - 04:30:00
2025-12-14 03:55:14.932105: Adjust idle time, charge 00:00:00-00:00:00 discharge 03:55:00-04:30:00
2025-12-14 03:55:14.932903: Adjust demand (idle) time computed is 04:30:00-23:59:00
2025-12-14 03:55:14.933036: Inverter 0 Current discharge target is already set to 10.0
2025-12-14 03:55:14.936834: Inverter 0 adjust target SoC for export to 0% based on requested all inverter SoC 0%
2025-12-14 03:55:14.936983: Inverter 0 Current charge limit is 100% and new target is 63%
2025-12-14 03:55:15.268166: Warn: Fox: Invalid parameter Parameters do not meet expectations. Please reenter:40257 from https://www.foxesscloud.com/op/v1/device/scheduler/enable
2025-12-14 03:55:15.269068: Fox: API Response failed after 10 retries for /op/v1/device/scheduler/enable
2025-12-14 03:55:17.060511: Inverter 0 write_and_poll_value: Wrote 63 to charge_limit, successfully now 63
2025-12-14 03:55:17.122782: Fox: New schedule for FoxInverterSN: [{'enable': 1, 'startHour': 0, 'startMinute': 0, 'endHour': 3, 'endMinute': 54, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 3, 'startMinute': 55, 'endHour': 4, 'endMinute': 29, 'workMode': 'ForceDischarge', 'fdSoc': 10, 'maxSoc': 63, 'fdPwr': 6000, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 4, 'startMinute': 30, 'endHour': 23, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}]
2025-12-14 03:55:17.123203: Fox: Debug: Setting scheduler for FoxInverterSN same=False current_enable=1 current_groups=[{'endHour': 3, 'fdPwr': 6000, 'minSocOnGrid': 63, 'workMode': 'SelfUse', 'fdSoc': 63, 'enable': 1, 'startHour': 0, 'maxSoc': 100, 'startMinute': 0, 'endMinute': 29}, {'endHour': 3, 'fdPwr': 6000, 'minSocOnGrid': 63, 'workMode': 'ForceCharge', 'fdSoc': 100, 'enable': 1, 'startHour': 3, 'maxSoc': 63, 'startMinute': 30, 'endMinute': 54}, {'endHour': 23, 'fdPwr': 6000, 'minSocOnGrid': 63, 'workMode': 'SelfUse', 'fdSoc': 63, 'enable': 1, 'startHour': 3, 'maxSoc': 100, 'startMinute': 55, 'endMinute': 59}, {'endHour': 0, 'fdPwr': 0, 'minSocOnGrid': 10, 'workMode': 'SelfUse', 'fdSoc': 100, 'enable': 0, 'startHour': 0, 'maxSoc': 100, 'startMinute': 0, 'endMinute': 0}, {'endHour': 0, 'fdPwr': 0, 'minSocOnGrid': 10, 'workMode': 'SelfUse', 'fdSoc': 100, 'enable': 0, 'startHour': 0, 'maxSoc': 100, 'startMinute': 0, 'endMinute': 0}, {'endHour': 0, 'fdPwr': 0, 'minSocOnGrid': 10, 'workMode': 'SelfUse', 'fdSoc': 100, 'enable': 0, 'startHour': 0, 'maxSoc': 100, 'startMinute': 0, 'endMinute': 0}, {'endHour': 0, 'fdPwr': 0, 'minSocOnGrid': 10, 'workMode': 'SelfUse', 'fdSoc': 100, 'enable': 0, 'startHour': 0, 'maxSoc': 100, 'startMinute': 0, 'endMinute': 0}, {'endHour': 0, 'fdPwr': 0, 'minSocOnGrid': 10, 'workMode': 'SelfUse', 'fdSoc': 100, 'enable': 0, 'startHour': 0, 'maxSoc': 100, 'startMinute': 0, 'endMinute': 0}] new_groups=[{'enable': 1, 'startHour': 0, 'startMinute': 0, 'endHour': 3, 'endMinute': 54, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 3, 'startMinute': 55, 'endHour': 4, 'endMinute': 29, 'workMode': 'ForceDischarge', 'fdSoc': 10, 'maxSoc': 63, 'fdPwr': 6000, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 4, 'startMinute': 30, 'endHour': 23, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}]
2025-12-14 03:55:17.123306: Fox: API Requesting POST /op/v1/device/scheduler/enable - data {'deviceSN': 'FoxInverterSN', 'groups': [{'enable': 1, 'startHour': 0, 'startMinute': 0, 'endHour': 3, 'endMinute': 54, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 3, 'startMinute': 55, 'endHour': 4, 'endMinute': 29, 'workMode': 'ForceDischarge', 'fdSoc': 10, 'maxSoc': 63, 'fdPwr': 6000, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 4, 'startMinute': 30, 'endHour': 23, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}]}
2025-12-14 03:55:17.123461: Fox: API Request: path /op/v1/device/scheduler/enable post True datain {'deviceSN': 'FoxInverterSN', 'groups': [{'enable': 1, 'startHour': 0, 'startMinute': 0, 'endHour': 3, 'endMinute': 54, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 3, 'startMinute': 55, 'endHour': 4, 'endMinute': 29, 'workMode': 'ForceDischarge', 'fdSoc': 10, 'maxSoc': 63, 'fdPwr': 6000, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 4, 'startMinute': 30, 'endHour': 23, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}]}
2025-12-14 03:55:17.140509: Pressed toggle button switch.predbat_fox_FoxInverterSN_battery_schedule_charge_write on Inverter 0
2025-12-14 03:55:17.141027: Inverter 0 Current reserve is 63%, already at target
2025-12-14 03:55:17.143792: Inverter 0 count register writes 2

**Comment by springfall2008** [comment]
Please check the latest release, this should be fixed

**Comment by davidjwood** [comment]
@springfall2008 The new v8.29.12+ Fox scheduler is calculating the slot times correctly, but forced exports are still broken in the same way in v8.29.11 because the parameters for the forced discharge slot are wrong (discharge target is set to 10.0 instead of the wanted value, fdSoc is less than minSocOnGrid, and a 40257 error results).

If I set Predbat to read only, and create a forced discharge slot in the FoxCloud 2.0 app with fdSoc 59, maxSoc 100, fdPwr 6000.0 (turns out that you don't need to clamp this to the export limit, contrary to my earlier suggestion) and minSocOnGrid 59, then the export proceeds as intended.

For a discharge slot, maxSoc really should be 100 in line 1393 of fox.py, not reserve. That fixes part of the problem.

The remaining part of the problem originates from line 1370 of fox.py, which causes soc to always be 10 for a forced discharge slot.

Temporarily, I have set the forced discharge parameters in line 1393 of fox.py in my installation to:
>{"enable": 1, "startHour": start_hour, "startMinute": start_minute, "endHour": end_hour, "endMinute": end_minute, "workMode": "ForceDischarge", "fdSoc": reserve, "maxSoc": 100, "fdPwr": power, "minSocOnGrid": reserve}

which behaves more sensibly, but misuses reserve as a sensible discharge soc.

Without that change to line 1393, this is what happens in v8.29.13:
>2025-12-18 21:50:13.179257: Inverter 0 Charge window will be: 2025-12-18 22:00:00+00:00 - 2025-12-18 22:20:00+00:00 - current SoC 63%, target 65%
2025-12-18 21:50:13.179663: Inverter 0 configuring charge window now (now 12-18 21:50:00 target set_window_minutes 30 charge start time 12-18 22:00:00
2025-12-18 21:50:13.186270: Adjust idle time, charge 22:00:00-22:20:00 discharge 00:00:00-00:00:00
2025-12-18 21:50:13.187491: Adjust demand (idle) time computed is 11:05:00-22:00:00
2025-12-18 21:50:13.187849: Next export window will be: 2025-12-18 22:20:00+00:00 - 2025-12-18 22:30:00+00:00 at reserve 59.0
2025-12-18 21:50:13.188271: Inverter 0 Adjust force export to True, change times from 04:20:00 - 04:30:00 to 22:20:00 - 22:30:00
2025-12-18 21:50:13.188322: Adjust idle time, charge 22:00:00-22:20:00 discharge 22:20:00-22:30:00
2025-12-18 21:50:13.188472: Adjust demand (idle) time computed is 11:05:00-22:00:00
2025-12-18 21:50:13.188569: Inverter 0 set new export start time to 22:20:00
2025-12-18 21:50:15.315629: Inverter 0 Wrote discharge_start_time to 22:20:00 successfully
2025-12-18 21:50:15.316373: Inverter 0 Set new export end time to 22:30:00 was 04:30:00
2025-12-18 21:50:17.390987: Inverter 0 Wrote discharge_end_time to 22:30:00 successfully
2025-12-18 21:50:17.392260: Inverter 0 Current discharge target is already set to 10.0
2025-12-18 21:50:19.463557: Inverter 0 Wrote scheduled_discharge_enable to True successfully and got on
2025-12-18 21:50:19.464184: Inverter 0 Turning on scheduled export
2025-12-18 21:50:19.510730: Fox: New schedule for 609H602055PC003: [{'enable': 1, 'startHour': 0, 'startMinute': 0, 'endHour': 21, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 22, 'startMinute': 0, 'endHour': 22, 'endMinute': 19, 'workMode': 'ForceCharge', 'fdSoc': 100, 'maxSoc': 65, 'fdPwr': 6000.0, 'minSocOnGrid': 65}, {'enable': 1, 'startHour': 22, 'startMinute': 20, 'endHour': 22, 'endMinute': 29, 'workMode': 'ForceDischarge', 'fdSoc': 10, 'maxSoc': 63, 'fdPwr': 6000, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 22, 'startMinute': 30, 'endHour': 23, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}]
2025-12-18 21:50:19.511152: Fox: Debug: Setting scheduler for 609H602055PC003 same=False current_enable=True current_groups=[{'enable': 1, 'startHour': 0, 'startMinute': 0, 'endHour': 21, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 22, 'startMinute': 0, 'endHour': 22, 'endMinute': 19, 'workMode': 'ForceCharge', 'fdSoc': 100, 'maxSoc': 65, 'fdPwr': 6000.0, 'minSocOnGrid': 65}, {'enable': 1, 'startHour': 22, 'startMinute': 20, 'endHour': 23, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}] new_groups=[{'enable': 1, 'startHour': 0, 'startMinute': 0, 'endHour': 21, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 22, 'startMinute': 0, 'endHour': 22, 'endMinute': 19, 'workMode': 'ForceCharge', 'fdSoc': 100, 'maxSoc': 65, 'fdPwr': 6000.0, 'minSocOnGrid': 65}, {'enable': 1, 'startHour': 22, 'startMinute': 20, 'endHour': 22, 'endMinute': 29, 'workMode': 'ForceDischarge', 'fdSoc': 10, 'maxSoc': 63, 'fdPwr': 6000, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 22, 'startMinute': 30, 'endHour': 23, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}]
2025-12-18 21:50:19.511295: Fox: API Requesting POST /op/v1/device/scheduler/enable - data {'deviceSN': '609H602055PC003', 'groups': [{'enable': 1, 'startHour': 0, 'startMinute': 0, 'endHour': 21, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 22, 'startMinute': 0, 'endHour': 22, 'endMinute': 19, 'workMode': 'ForceCharge', 'fdSoc': 100, 'maxSoc': 65, 'fdPwr': 6000.0, 'minSocOnGrid': 65}, {'enable': 1, 'startHour': 22, 'startMinute': 20, 'endHour': 22, 'endMinute': 29, 'workMode': 'ForceDischarge', 'fdSoc': 10, 'maxSoc': 63, 'fdPwr': 6000, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 22, 'startMinute': 30, 'endHour': 23, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}]}
2025-12-18 21:50:19.511732: Fox: API Request: path /op/v1/device/scheduler/enable post True datain {'deviceSN': '609H602055PC003', 'groups': [{'enable': 1, 'startHour': 0, 'startMinute': 0, 'endHour': 21, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 22, 'startMinute': 0, 'endHour': 22, 'endMinute': 19, 'workMode': 'ForceCharge', 'fdSoc': 100, 'maxSoc': 65, 'fdPwr': 6000.0, 'minSocOnGrid': 65}, {'enable': 1, 'startHour': 22, 'startMinute': 20, 'endHour': 22, 'endMinute': 29, 'workMode': 'ForceDischarge', 'fdSoc': 10, 'maxSoc': 63, 'fdPwr': 6000, 'minSocOnGrid': 63}, {'enable': 1, 'startHour': 22, 'startMinute': 30, 'endHour': 23, 'endMinute': 59, 'workMode': 'SelfUse', 'fdSoc': 63, 'maxSoc': 100, 'fdPwr': 6000.0, 'minSocOnGrid': 63}]}
2025-12-18 21:50:19.527871: Pressed toggle button switch.predbat_fox_609h602055pc003_battery_schedule_charge_write on Inverter 0
2025-12-18 21:50:19.528012: Sleeping (workaround) as start/end of discharge window was just adjusted
2025-12-18 21:50:19.680745: Warn: Fox: Invalid parameter Parameters do not meet expectations. Please reenter:40257 from https://www.foxesscloud.com/op/v1/device/scheduler/enable
2025-12-18 21:50:19.681812: Fox: API Response failed after 10 retries for /op/v1/device/scheduler/enable
2025-12-18 21:50:49.532537: Setting charging SoC to 65% as per target for when charge window starts
2025-12-18 21:50:49.533686: Inverter 0 adjust target SoC for charge to 65% (14.98kWh/23.04kWh 23.04kWh) based on going from 63% -> 65% total add is 0.46kWh and this battery needs to add 0.46kWh to get to 14.98kWh
2025-12-18 21:50:49.533831: Inverter 0 Current Target SoC is 65%, already at target
2025-12-18 21:50:49.534449: Inverter 0 Current reserve is 63%, already at target
2025-12-18 21:50:49.534792: Inverter 0 count register writes 3

**Comment by springfall2008** [comment]
What version did you try, I've done some more fixes over the last week and it seems to be okay for others?

**Comment by davidjwood** [comment]
@springfall2008 The failure in my last comment was on v8.29.13.

Edit to add: Your recent work has dramatically improved Fox Cloud support, but I still maintain that there is an issue with forced discharge slot parameters in your current code, as I have explained in my earlier comment. Perhaps the issue is that forced discharges are pretty rare at the moment. Forced discharge only happened in my case because there was a very cheap night of Octopus Agile imports, I'm on the fixed 15p Octopus export tariff, so Predbat charged my batteries with some very cheap electricity, which it subsequently re-exported.

**Comment by springfall2008** [comment]
Are you saying that the problem is fdSoc being set less than minsocongrid?

**Comment by springfall2008** [comment]
Okay, looking at the code I've made a fix to prevent fdSoc from being less than minSocOnGrid. 

I don't think the fdPwr should be capped at the export limit or it will not cover the house load as well, the inverter should do that for you.

I'll make a new release for you to test.

**Comment by springfall2008** [comment]
Let me know if the new release works

**Comment by davidjwood** [comment]
It works well now. Many thanks for all your efforts.
